{
  "hash": "50b81bcd152c4e5bf1d5229e8199c9c1",
  "result": {
    "engine": "knitr",
    "markdown": "---\ntitle: \"Danish diabetes data\"\nauthor: \"Henrik Vitus Bering Laursen\"\ndate: \"2025-06-17\"\ncategories:\n  - diabetes\n  - data exploration\n  - joins\n  - survival analysis\nformat:\n  html:\n    toc: true\n    number-sections: true\n    fig-width: 8\n    fig-height: 6\ndraft: false\nimage: thumbnail.jpg\n---\n\n## Purpose\n\nI remember using the `Epi::steno2` data-sets when taking a short course on multistate survival analysis with the creator of the package, [Bendix Carstensen](https://bendixcarstensen.com/).\n\nThat was quite fun but also daunting to be sitting in a room full of mathematicians and people who actually knew the nitty gritty of survival analysis and the math behind it.\n\nI think I would just want to do something very basic here, though:\n\n- A) Playing around with joining the different data-sets\n- B) Examine the data-sets and visualize the contents\n- C) Creating a simple Cox Proportional Hazards model, comparing the risk of cardiovascular event between the two treatment groups in the data-set\n  - Probably also controlling for some important factors\n- D) Deliver some sort of conclusion about these data\n\nSo lets start looking at it!\n\n## Load\n\nThe data-sets can be loaded directly from the `Epi` library, through `data()`\n\n\n::: {.cell}\n\n:::\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\ndata(\"steno2\")\ndata(\"st2clin\")\ndata(\"st2alb\")\n```\n:::\n\n\nAlrighty now that they are loaded lets look at their structure. **Ofcourse, I am completely ignoring the description in the documentation in the `Epi()` package, which describes how the data-sets are structured.**\n\n\n::: {.cell}\n\n```{.r .cell-code}\nstr(steno2)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n'data.frame':\t160 obs. of  14 variables:\n $ id      : num  1 2 3 4 5 6 7 8 9 10 ...\n $ allo    : Factor w/ 2 levels \"Int\",\"Conv\": 1 1 2 2 2 2 2 1 1 1 ...\n $ sex     : Factor w/ 2 levels \"F\",\"M\": 2 2 2 2 2 2 1 2 2 2 ...\n $ baseCVD : num  0 0 0 0 0 1 0 0 0 0 ...\n $ deathCVD: num  0 0 0 0 1 0 0 0 1 0 ...\n $ doBth   : Date, format: \"1932-04-11\" \"1946-11-09\" ...\n $ doDM    : Date, format: \"1991-01-21\" \"1982-01-30\" ...\n $ doBase  : Date, format: \"1993-04-30\" \"1993-06-08\" ...\n $ doCVD1  : Date, format: \"2014-05-24\" \"2009-03-15\" ...\n $ doCVD2  : Date, format: NA \"2009-07-02\" ...\n $ doCVD3  : Date, format: NA \"2010-02-16\" ...\n $ doESRD  : Date, format: \"NaN\" \"NaN\" ...\n $ doEnd   : Date, format: \"2014-10-12\" \"2014-08-04\" ...\n $ doDth   : Date, format: NA NA ...\n```\n\n\n:::\n\n```{.r .cell-code}\nstr(st2clin)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n'data.frame':\t750 obs. of  5 variables:\n $ id  : num  1 2 3 4 5 6 7 8 9 10 ...\n $ doV : Date, format: \"1993-05-07\" \"1993-05-05\" ...\n $ a1c : num  87.3 66.5 73 61.2 102.7 ...\n $ chol: num  3.9 6.6 5.6 5.2 6 4.8 8.6 5.1 4.2 5.4 ...\n $ crea: num  83 83 68 97 149 55 56 78 123 79 ...\n```\n\n\n:::\n\n```{.r .cell-code}\nstr(st2alb)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n'data.frame':\t563 obs. of  3 variables:\n $ id   : num  1 1 1 1 1 2 2 2 2 2 ...\n $ doTr : Date, format: \"1993-06-12\" \"1995-05-13\" ...\n $ state: Factor w/ 3 levels \"Norm\",\"Mic\",\"Mac\": 2 1 2 1 2 1 2 3 2 2 ...\n```\n\n\n:::\n:::\n\n\nIt looks like `steno2` and `st2clin` are one row per subject, and `st2alb` is multiple, but that doesn't make sense given the amount of rows. We can see how many id's, the unique identifier for each person, are present, and if there is one row per subject it should be close to the amount of subjects.\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# create a 1 for each time there is an ID\nid_test1 <- steno2 |> count(id)\nhead(id_test1)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n  id n\n1  1 1\n2  2 1\n3  3 1\n4  4 1\n5  5 1\n6  6 1\n```\n\n\n:::\n\n```{.r .cell-code}\n# different numbers on those counts\nid_test2 <- id_test1 |>  summarize(n=sum(n), idcount = max(id), sum = sum(id))\nid_test2\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n    n idcount   sum\n1 160     176 13650\n```\n\n\n:::\n:::\n\n\nAlright. So it is clear that only `steno2` has one row per subject because the number of id's that occur equal the number of unique rows.\n\nLets see about the others\n\n\n::: {.cell}\n\n```{.r .cell-code}\nst2alb |> count(id) |> summarize(n=sum(n), idcount = max(id), sum = sum(id))\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n    n idcount   sum\n1 563     176 13187\n```\n\n\n:::\n\n```{.r .cell-code}\nst2clin |> count(id) |> summarize(n=sum(n), idcount = max(id), sum = sum(id))\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n    n idcount   sum\n1 750     176 13650\n```\n\n\n:::\n:::\n\n\nOk so the `st2*` datasets have more than one row per subject, but there is a strange lower sum in `st2alb` than the other datasets.\n\nCould it be that there are missing subjects in that dataset?\n\n\n::: {.cell}\n\n:::\n\n\n### A) Joining\n\nNow, first, what would the purpose be of joining these data-sets together?\n\nThere could be many reasons and I will touch upon some of them:\n\n- adding demographic characteristics from one data-set to another to stratify analysis\n- find things that are in one data-set but not in another\n\nFor example, the `st2clin` and `st2alb` data-sets do not have the categories for each id from the `steno2` data-set, such as sex and allocation.\n\nAlso, continuing from the previous section, were there any missing people in `st2alb`? There was a possible indication of it, which can be explored with a filtering join, more specifically, an anti_join, using the `anti_join()` function.\n\n  anti_join() return all rows from x without a match in y\n\nSo let's try to see if there are any missing.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nanti_join(steno2, st2alb, by = \"id\")\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n   id allo sex baseCVD deathCVD      doBth       doDM     doBase     doCVD1\n1  83  Int   M       0        1 1930-12-23 1989-06-28 1992-12-22 1994-12-04\n2 102  Int   M       0        1 1935-04-09 1990-03-19 1993-07-17 1995-04-23\n3 128 Conv   M       0        0 1937-03-14 1989-02-16 1993-10-03 1995-11-13\n4 150 Conv   F       0        0 1946-02-18 1989-10-29 1993-12-24       <NA>\n      doCVD2     doCVD3     doESRD      doEnd      doDth\n1 1994-12-12       <NA>        NaN 1994-11-15 1994-12-19\n2       <NA>       <NA>        NaN 1995-03-30 1995-05-02\n3 2003-08-07 2004-05-31 1999-12-26 2005-05-19 2005-05-18\n4       <NA>       <NA>        NaN 2014-08-27       <NA>\n```\n\n\n:::\n:::\n\n\n\n::: {.cell}\n::: {.cell-output .cell-output-stdout}\n\n```\n [1] id       allo     sex      baseCVD  deathCVD doBth    doDM     doBase  \n [9] doCVD1   doCVD2   doCVD3   doESRD   doEnd    doDth   \n<0 rows> (or 0-length row.names)\n```\n\n\n:::\n:::\n\n\nIt seems that id 83, 102, 128, and 150 are missing from `st2alb`. They are not missing from `st2clin` - I checked in a hidden code chunk. Since it's stated in the documentation that it's a data-set about transitions between states of albuminuria, perhaps one could assume that these individuals simply did not transition?\n\n## Output\n### B) Table\n\nOf course, the good old `summary()` function might be worth to do to get a good overview of the three data-sets. First we do `steno2` demographics.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nsummary(steno2)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n       id           allo    sex        baseCVD          deathCVD     \n Min.   :  1.00   Int :80   F: 41   Min.   :0.0000   Min.   :0.0000  \n 1st Qu.: 40.75   Conv:80   M:119   1st Qu.:0.0000   1st Qu.:0.0000  \n Median : 82.50                     Median :0.0000   Median :0.0000  \n Mean   : 85.31                     Mean   :0.1375   Mean   :0.2375  \n 3rd Qu.:130.25                     3rd Qu.:0.0000   3rd Qu.:0.0000  \n Max.   :176.00                     Max.   :1.0000   Max.   :1.0000  \n                                                                     \n     doBth                 doDM                doBase          \n Min.   :1926-07-13   Min.   :1962-06-21   Min.   :1992-12-22  \n 1st Qu.:1932-07-18   1st Qu.:1982-10-01   1st Qu.:1993-03-23  \n Median :1937-03-12   Median :1987-05-02   Median :1993-06-11  \n Mean   :1938-06-03   Mean   :1986-01-15   Mean   :1993-07-22  \n 3rd Qu.:1944-11-28   3rd Qu.:1990-05-03   3rd Qu.:1993-11-15  \n Max.   :1956-04-07   Max.   :1994-02-07   Max.   :1994-06-14  \n                                                               \n     doCVD1               doCVD2               doCVD3          \n Min.   :1993-03-17   Min.   :1994-08-05   Min.   :1995-12-16  \n 1st Qu.:1997-02-16   1st Qu.:1999-04-18   1st Qu.:2001-11-23  \n Median :2001-04-03   Median :2002-12-20   Median :2004-12-13  \n Mean   :2001-12-18   Mean   :2003-10-04   Mean   :2005-01-11  \n 3rd Qu.:2006-07-20   3rd Qu.:2008-07-20   3rd Qu.:2009-06-03  \n Max.   :2014-05-30   Max.   :2014-03-26   Max.   :2012-07-21  \n NA's   :41           NA's   :84           NA's   :117         \n     doESRD               doEnd                doDth           \n Min.   :1998-02-18   Min.   :1994-11-16   Min.   :1994-12-19  \n 1st Qu.:2002-09-25   1st Qu.:2002-09-18   1st Qu.:2000-05-21  \n Median :2008-05-08   Median :2010-02-11   Median :2004-03-06  \n Mean   :2006-07-17   Mean   :2008-08-29   Mean   :2004-05-24  \n 3rd Qu.:2009-07-29   3rd Qu.:2014-09-25   3rd Qu.:2009-06-04  \n Max.   :2014-07-07   Max.   :2014-12-31   Max.   :2014-02-16  \n NA's   :145                               NA's   :67          \n```\n\n\n:::\n:::\n\nBut I kinda want to mainly do graphs here.\n\n### B) Graphs\n\n#### Some distributions\n\nNow, I love me some functions, and I feel like seeing the distribution of all the different date variables via histograms.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nplot_histo_spam <- function(df,histovar) {\nout <- ggplot(df) +\n  geom_histogram(mapping = aes( {{histovar}} ))\n\n  return(out)\n}\n\nplot_histo_spam(steno2,doBth)\n```\n\n::: {.cell-output .cell-output-stderr}\n\n```\n`stat_bin()` using `bins = 30`. Pick better value with `binwidth`.\n```\n\n\n:::\n\n::: {.cell-output-display}\n![](index_files/figure-html/first attempt, going over date vars-1.png){width=768}\n:::\n\n```{.r .cell-code}\nplot_histo_spam(steno2,doDM)\n```\n\n::: {.cell-output .cell-output-stderr}\n\n```\n`stat_bin()` using `bins = 30`. Pick better value with `binwidth`.\n```\n\n\n:::\n\n::: {.cell-output-display}\n![](index_files/figure-html/first attempt, going over date vars-2.png){width=768}\n:::\n\n```{.r .cell-code}\nplot_histo_spam(steno2,doBase)\n```\n\n::: {.cell-output .cell-output-stderr}\n\n```\n`stat_bin()` using `bins = 30`. Pick better value with `binwidth`.\n```\n\n\n:::\n\n::: {.cell-output-display}\n![](index_files/figure-html/first attempt, going over date vars-3.png){width=768}\n:::\n:::\n\n\nBut this should be doable in a smarter way. A `facet_wrap()` over each of the date variables..\n\n\n::: {.cell}\n\n```{.r .cell-code}\nplot_histospam_faceted <- function(data, prefix = \"do\") {\n  data |>\n    select(starts_with(prefix)) |>\n    pivot_longer(everything()) |> # everything() turns varnames into a column, and their values into a separate column\n    ggplot(aes(value)) +\n      geom_histogram(colour = \"white\") +\n      facet_wrap(~ name, scales = \"free_x\") +   # one panel per variable\n      labs(x = NULL)\n}\n\nplot_histospam_faceted(steno2)\n```\n\n::: {.cell-output .cell-output-stderr}\n\n```\n`stat_bin()` using `bins = 30`. Pick better value with `binwidth`.\n```\n\n\n:::\n\n::: {.cell-output .cell-output-stderr}\n\n```\nWarning: Removed 454 rows containing non-finite outside the scale range\n(`stat_bin()`).\n```\n\n\n:::\n\n::: {.cell-output-display}\n![](index_files/figure-html/second attempt, going over date vars-1.png){width=768}\n:::\n\n```{.r .cell-code}\nplot_histospam_faceted(st2clin)\n```\n\n::: {.cell-output .cell-output-stderr}\n\n```\n`stat_bin()` using `bins = 30`. Pick better value with `binwidth`.\n```\n\n\n:::\n\n::: {.cell-output-display}\n![](index_files/figure-html/second attempt, going over date vars-2.png){width=768}\n:::\n\n```{.r .cell-code}\nplot_histospam_faceted(st2alb)\n```\n\n::: {.cell-output .cell-output-stderr}\n\n```\n`stat_bin()` using `bins = 30`. Pick better value with `binwidth`.\n```\n\n\n:::\n\n::: {.cell-output-display}\n![](index_files/figure-html/second attempt, going over date vars-3.png){width=768}\n:::\n:::\n\n\nNow those are some fine basic plots!\n\nFor `steno2`, it shows some slight right skewed `doBase`, and left-skewed `doDM` and `doEnd`. for the two `st2*` data-sets, it shows quite a right skew.\n\n**Basically**:\n\n- most of the signups to the trial occurred in the beginning\n- most of the CVD (cardiovascular) and death events occurred evenly-ish\n- most of the diabetes diagnoses occurred late\n- not much ESRD (end-stage renal disease) occurred\n\n#### Distributions by sex\n\nNow I want to figure out how to do it while grouping the histograms by sex.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nplot_histospam_faceted_sex <- function(data, prefix = \"do\") {\n  data |>\n    select(sex, starts_with(prefix)) |>\n    pivot_longer(-sex,\n                 names_to = \"name\",\n                 values_to = \"value\") |>\n    ggplot(aes(value, fill = sex)) +\n      geom_histogram(\n        position = \"dodge\",\n        colour = \"white\") +\n      facet_wrap(~ name, scales = \"free_x\") +   # one panel per variable\n      labs(x = NULL)\n}\n\nplot_histospam_faceted_sex(steno2)\n```\n\n::: {.cell-output .cell-output-stderr}\n\n```\n`stat_bin()` using `bins = 30`. Pick better value with `binwidth`.\n```\n\n\n:::\n\n::: {.cell-output .cell-output-stderr}\n\n```\nWarning: Removed 454 rows containing non-finite outside the scale range\n(`stat_bin()`).\n```\n\n\n:::\n\n::: {.cell-output-display}\n![](index_files/figure-html/histograms, faceted, sex-1.png){width=768}\n:::\n:::\n\n\nOk. Not much of a difference at a glance.\n\n#### Distributions by treatment groups\n\nPerhaps it would be more relevant to see if there was some kind of difference between the two intervention groups?\n\n\n::: {.cell}\n\n```{.r .cell-code}\nplot_histospam_faceted_allo <- function(data, prefix = \"do\") {\n  data |>\n    select(allo, starts_with(prefix)) |>\n    pivot_longer(-allo,\n                 names_to = \"name\",\n                 values_to = \"value\") |>\n    ggplot(aes(value, fill = allo)) +\n      geom_histogram(\n        position = \"identity\",\n        alpha    = 0.5,\n        colour = \"white\") +\n      facet_wrap(~ name, scales = \"free_x\") +   # one panel per variable\n      labs(x = NULL)\n}\n\nplot_histospam_faceted_allo(steno2)\n```\n\n::: {.cell-output .cell-output-stderr}\n\n```\n`stat_bin()` using `bins = 30`. Pick better value with `binwidth`.\n```\n\n\n:::\n\n::: {.cell-output .cell-output-stderr}\n\n```\nWarning: Removed 454 rows containing non-finite outside the scale range\n(`stat_bin()`).\n```\n\n\n:::\n\n::: {.cell-output-display}\n![](index_files/figure-html/histograms, faceted, allocation group-1.png){width=768}\n:::\n:::\n\n\nOk so already here its possible to see some apparent differences between the two groups.\n\n- the `Conv` allocation group, which must be those allocated to conventional treatment, whatever that was, have more events of CVD, especially of the third CVD event. As well as earlier diabetes mellitus (DM) diagnoses. This is probably an indication of the future results of the survival analysis.\n- `Int` group, likely the intervention group, seems to have less deaths and later DM diagnoses\n\n**Remember, these are two groups of equal number**, which can make it easier to conclude that there is a difference, at least initially and visually.\n\nNow. With the help of some AI, I made the function below which can produce different types of `facet_*` plots , but I choose the `facet_grid`, because its interesting to look at.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nsteno2 |>\n    select(allo, starts_with(\"do\")) |>\n    pivot_longer(-allo, names_to = \"variable\", values_to = \"value\") |>\n    ggplot(aes(value, fill = allo)) +\n    geom_histogram(position = \"identity\", colour = \"white\") +\n        facet_grid(rows = vars(allo), cols = vars(variable)) +\n    #scale_x_continuous(breaks = floor(min(value)):ceiling(max(value)),\n    #               labels  = scales::number_format(accuracy = 1)) +\n    labs(x = NULL, fill = \"Allocation\") +\n    theme_minimal() +\n    theme(axis.text.x = element_text(angle = 45, vjust = .5, hjust = 1))\n```\n\n::: {.cell-output .cell-output-stderr}\n\n```\n`stat_bin()` using `bins = 30`. Pick better value with `binwidth`.\n```\n\n\n:::\n\n::: {.cell-output .cell-output-stderr}\n\n```\nWarning: Removed 454 rows containing non-finite outside the scale range\n(`stat_bin()`).\n```\n\n\n:::\n\n::: {.cell-output-display}\n![](index_files/figure-html/histograms, faceted, complicated-1.png){width=768}\n:::\n:::\n\n\nThis might be information overload to such a degree that not much is gained from it.\n\n### C) Model\n\nTo perform a basic Cox Proportional Hazards model, we can use the `survival` package.\n\nI want to do the following, just because that's what I learned in the olden PhD studying days, mainly from the Basic Biostats courses from Aarhus University:\n\n- Survival set the data\n- Visualise follow-up\n- Plot Kaplan Meier survival function\n- Cox model\n  - Estimate\n  - Observed vs fitted survival curves\n  - Testing proportional hazards assumption\n\nLet's just quickly and without much thinking (thats always good), decide what the start, stop, outcome, and other variables should be.\n\n- data: `steno2`\n  - comparison: death `doDth` for intervention groups `allo`\n  - start date: `doBase`\n  - censor date: `doEnd`\n  - outcome event: `doDth`\n  - exit of study: earliest of `doEnd` and `doDth`\n\nSo, super basic, and does not take anything into account, such as competing events (`doCVD*` or `doESRD`) or baseline differences in risk of CVD (`baseCVD`).\n\n\n\n#### Survival set the data\n\nFirst we create the needed variables and check it.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nsteno2 <- steno2 |>\n  mutate(\n    doExit = coalesce(doDth, doEnd),\n    time_days = difftime(\n      coalesce(steno2$doDth, steno2$doEnd),\n      steno2$doBase,\n      units='days'),\n    time_yrs = as.numeric(time_days / 365.25),\n    event_num = if_else(!is.na(doDth),1,0),\n    event = factor(event_num, levels = c(0, 1), labels = c(\"Censored\", \"Dead\"))\n  )\n\nglimpse(steno2)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nRows: 160\nColumns: 19\n$ id        <dbl> 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 1…\n$ allo      <fct> Int, Int, Conv, Conv, Conv, Conv, Conv, Int, Int, Int, Int, …\n$ sex       <fct> M, M, M, M, M, M, F, M, M, M, M, M, M, M, F, M, F, F, M, M, …\n$ baseCVD   <dbl> 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 1, 0, 0, 0, 1, 0, 0, 0, 0, …\n$ deathCVD  <dbl> 0, 0, 0, 0, 1, 0, 0, 0, 1, 0, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, …\n$ doBth     <date> 1932-04-11, 1946-11-09, 1943-06-07, 1944-11-01, 1935-12-22,…\n$ doDM      <date> 1991-01-21, 1982-01-30, 1982-07-17, 1976-10-28, 1986-05-06,…\n$ doBase    <date> 1993-04-30, 1993-06-08, 1993-05-17, 1993-05-04, 1993-03-23,…\n$ doCVD1    <date> 2014-05-24, 2009-03-15, 2001-08-28, 1995-05-31, 1993-12-16,…\n$ doCVD2    <date> NA, 2009-07-02, NA, 1997-06-26, 1994-08-05, NA, 2006-02-27,…\n$ doCVD3    <date> NA, 2010-02-16, NA, 2003-06-17, 1997-12-25, NA, NA, NA, NA,…\n$ doESRD    <date> NaN, NaN, NaN, NaN, 1998-02-18, 2014-07-07, NaN, 2009-03-06…\n$ doEnd     <date> 2014-10-12, 2014-08-04, 2001-08-21, 2003-06-11, 1998-01-18,…\n$ doDth     <date> NA, NA, 2001-09-20, 2003-06-24, 1998-02-25, NA, 2006-04-24,…\n$ doExit    <date> 2014-10-12, 2014-08-04, 2001-09-20, 2003-06-24, 1998-02-25,…\n$ time_days <drtn> 7834.3828 days, 7726.4177 days, 3048.4091 days, 3703.4893 d…\n$ time_yrs  <dbl> 21.449371, 21.153779, 8.346089, 10.139601, 4.929256, 21.4398…\n$ event_num <dbl> 0, 0, 1, 1, 1, 0, 1, 1, 1, 1, 1, 1, 0, 1, 0, 1, 0, 0, 0, 0, …\n$ event     <fct> Censored, Censored, Dead, Dead, Dead, Censored, Dead, Dead, …\n```\n\n\n:::\n:::\n\n\n#### Visualise follow-up\n\nThen, because I like it as an overview, a swimmer plot of the follow-up times.\n\nsimple first:\n\n\n::: {.cell}\n\n```{.r .cell-code}\nswim_plot_1 <- steno2 |>\n  mutate(id = fct_reorder(as.factor(id), time_yrs)) |>\n  ggplot(aes(x = doBase,\n             xend = doExit,\n             y = id)) +\n  geom_segment(color = \"grey\") +\n  geom_point(aes(x = doExit, shape = event)) +\n  geom_point(aes(x = doDth, shape = event))\nswim_plot_1\n```\n\n::: {.cell-output .cell-output-stderr}\n\n```\nWarning: Removed 67 rows containing missing values or values outside the scale range\n(`geom_point()`).\n```\n\n\n:::\n\n::: {.cell-output-display}\n![](index_files/figure-html/swimplot followup simple-1.png){width=768}\n:::\n:::\n\n\nLooks good, but a tiny bit messy with the - although accurate - different starting times.\n\nLets do one with baseline time set to 0. This makes it easier to compare the follow-up times, which is more interesting for the analysis than calendar times.\n\nThe latter would probably be of more interest to an investigator trying to figure out when people signed up, or something.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nswim_plot_2 <- steno2 |>\n  mutate(\n    id = fct_reorder(as.factor(id), time_yrs),\n    t0 = 0) |>\n  ggplot(aes(x = t0,\n             xend = time_yrs,\n             y = id)) +\n  geom_segment(color = \"grey\") +\n  geom_point(aes(x = time_yrs, shape = event, colour = event)) +\n  theme_minimal()\nswim_plot_2\n```\n\n::: {.cell-output-display}\n![](index_files/figure-html/swimplot followup simple base is 0-1.png){width=768}\n:::\n:::\n\n\nHere we have the x-axis in years since baseline.\n\nNow, I have a sense that `doExit` and `doDth` are the same, meaning that plots that use `doExit` end up having two shapes for subjects that died.\n\nHow can I make it so that there are different shapes for each event? I can just take the previous plot and add to it.\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nswim_plot_3 <- swim_plot_2 +\n  scale_shape_manual(values = c(Censored = 17, Dead = 4)) +\n  scale_colour_manual(values = c(Censored = \"black\", Dead = \"red\"))\nswim_plot_3\n```\n\n::: {.cell-output-display}\n![](index_files/figure-html/swimplot different shapes for event-1.png){width=768}\n:::\n:::\n\nOk that looks fine. Now I want to make the final plot for this and move on.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nswim_plot_4 <- swim_plot_3 +\n  labs(\n    x = \"Follow-up time in years since baseline\",\n    y = \"Subject sorted by follow-up\",\n    title = \"Follow-up per subject, years since baseline\") +\n  theme(\n    axis.text.y = element_blank(),\n    axis.ticks.y = element_blank(),\n    panel.grid.minor = element_blank(),\n    panel.grid.major = element_blank()\n    )\nswim_plot_4\n```\n\n::: {.cell-output-display}\n![](index_files/figure-html/swimplot followup final-1.png){width=768}\n:::\n\n```{.r .cell-code}\nggsave(\"thumbnail.jpg\", plot = last_plot(), width = 6, height = 4) # saved as thumbnail\n```\n:::\n\n\nA nice little plot showing an overview of the length of follow-up for the subjects in the study.\n\nNot exactly sure how it is useful except for my own sake - I just like to know *visually* what my data looks like.\n\n#### Disclaimer {#sec-output-model-disclaimer}\n\nI am not a statistician, so whatever is correct of below, is due to the wise words and lectures I have remembered from people who actually know what they are talking about. Many statistical results, especially when you wish to talk inference (X causes Y), require careful consideration of subjective priors, demographics, causal effects, and biases such as effect modifiers, confounders, selection bias, etc.\n\nNow - with that out of the way: LETS CLAIM SOME THINGS!\n\n#### Plot Kaplan Meier survival function\n\nNow, less fiddling around with plots, and more looking at survival analysis.\n\nThe Kaplan meier estimator on a plot is wonderful for portraying differences in survival times. First step we have is to fit the data.\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# Overall, by treatment allocation, subset into sex\nkm_os <- survfit(Surv(time_yrs, event_num) ~ 1, data = steno2)\nkm_allo <- survfit(Surv(time_yrs, event_num) ~ allo, data = steno2)\nkm_sex <- survfit(Surv(time_yrs, event_num) ~ sex, data = steno2)\nkm_allo_sex <- survfit(Surv(time_yrs, event_num) ~ allo + sex, data = steno2)\n\n# Summarising, showing just the first 10 years\nsummary(km_os, times=c(0:10))\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nCall: survfit(formula = Surv(time_yrs, event_num) ~ 1, data = steno2)\n\n time n.risk n.event survival std.err lower 95% CI upper 95% CI\n    0    160       0    1.000 0.00000        1.000        1.000\n    1    160       0    1.000 0.00000        1.000        1.000\n    2    158       2    0.988 0.00878        0.970        1.000\n    3    155       3    0.969 0.01376        0.942        0.996\n    4    154       1    0.963 0.01502        0.934        0.992\n    5    148       6    0.925 0.02082        0.885        0.967\n    6    143       5    0.894 0.02436        0.847        0.943\n    7    137       6    0.856 0.02774        0.804        0.912\n    8    131       6    0.819 0.03045        0.761        0.881\n    9    125       6    0.781 0.03268        0.720        0.848\n   10    116       9    0.725 0.03530        0.659        0.798\n```\n\n\n:::\n\n```{.r .cell-code}\nsummary(km_allo, times=c(0:10))\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nCall: survfit(formula = Surv(time_yrs, event_num) ~ allo, data = steno2)\n\n                allo=Int \n time n.risk n.event survival std.err lower 95% CI upper 95% CI\n    0     80       0    1.000  0.0000        1.000        1.000\n    1     80       0    1.000  0.0000        1.000        1.000\n    2     78       2    0.975  0.0175        0.941        1.000\n    3     77       1    0.963  0.0212        0.922        1.000\n    4     76       1    0.950  0.0244        0.903        0.999\n    5     75       1    0.938  0.0271        0.886        0.992\n    6     73       2    0.913  0.0316        0.853        0.977\n    7     70       3    0.875  0.0370        0.805        0.951\n    8     66       4    0.825  0.0425        0.746        0.913\n    9     64       2    0.800  0.0447        0.717        0.893\n   10     63       1    0.788  0.0457        0.703        0.882\n\n                allo=Conv \n time n.risk n.event survival std.err lower 95% CI upper 95% CI\n    0     80       0    1.000  0.0000        1.000        1.000\n    1     80       0    1.000  0.0000        1.000        1.000\n    2     80       0    1.000  0.0000        1.000        1.000\n    3     78       2    0.975  0.0175        0.941        1.000\n    4     78       0    0.975  0.0175        0.941        1.000\n    5     73       5    0.913  0.0316        0.853        0.977\n    6     70       3    0.875  0.0370        0.805        0.951\n    7     67       3    0.838  0.0412        0.760        0.922\n    8     65       2    0.813  0.0436        0.731        0.903\n    9     61       4    0.763  0.0476        0.675        0.862\n   10     53       8    0.663  0.0529        0.567        0.775\n```\n\n\n:::\n\n```{.r .cell-code}\nsummary(km_sex, times=c(0:10))\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nCall: survfit(formula = Surv(time_yrs, event_num) ~ sex, data = steno2)\n\n                sex=F \n time n.risk n.event survival std.err lower 95% CI upper 95% CI\n    0     41       0    1.000  0.0000        1.000        1.000\n    1     41       0    1.000  0.0000        1.000        1.000\n    2     41       0    1.000  0.0000        1.000        1.000\n    3     40       1    0.976  0.0241        0.930        1.000\n    4     40       0    0.976  0.0241        0.930        1.000\n    5     40       0    0.976  0.0241        0.930        1.000\n    6     39       1    0.951  0.0336        0.888        1.000\n    7     37       2    0.902  0.0463        0.816        0.998\n    8     34       3    0.829  0.0588        0.722        0.953\n    9     31       3    0.756  0.0671        0.635        0.900\n   10     29       2    0.707  0.0711        0.581        0.861\n\n                sex=M \n time n.risk n.event survival std.err lower 95% CI upper 95% CI\n    0    119       0    1.000  0.0000        1.000        1.000\n    1    119       0    1.000  0.0000        1.000        1.000\n    2    117       2    0.983  0.0118        0.960        1.000\n    3    115       2    0.966  0.0165        0.935        0.999\n    4    114       1    0.958  0.0184        0.923        0.995\n    5    108       6    0.908  0.0266        0.857        0.961\n    6    104       4    0.874  0.0304        0.816        0.936\n    7    100       4    0.840  0.0336        0.777        0.909\n    8     97       3    0.815  0.0356        0.748        0.888\n    9     94       3    0.790  0.0373        0.720        0.867\n   10     87       7    0.731  0.0406        0.656        0.815\n```\n\n\n:::\n\n```{.r .cell-code}\nsummary(km_allo_sex, times=c(0:10))\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nCall: survfit(formula = Surv(time_yrs, event_num) ~ allo + sex, data = steno2)\n\n                allo=Int, sex=F \n time n.risk n.event survival std.err lower 95% CI upper 95% CI\n    0     17       0    1.000  0.0000        1.000            1\n    1     17       0    1.000  0.0000        1.000            1\n    2     17       0    1.000  0.0000        1.000            1\n    3     17       0    1.000  0.0000        1.000            1\n    4     17       0    1.000  0.0000        1.000            1\n    5     17       0    1.000  0.0000        1.000            1\n    6     17       0    1.000  0.0000        1.000            1\n    7     17       0    1.000  0.0000        1.000            1\n    8     15       2    0.882  0.0781        0.742            1\n    9     14       1    0.824  0.0925        0.661            1\n   10     14       0    0.824  0.0925        0.661            1\n\n                allo=Int, sex=M \n time n.risk n.event survival std.err lower 95% CI upper 95% CI\n    0     63       0    1.000  0.0000        1.000        1.000\n    1     63       0    1.000  0.0000        1.000        1.000\n    2     61       2    0.968  0.0221        0.926        1.000\n    3     60       1    0.952  0.0268        0.901        1.000\n    4     59       1    0.937  0.0307        0.878        0.999\n    5     58       1    0.921  0.0341        0.856        0.990\n    6     56       2    0.889  0.0396        0.815        0.970\n    7     53       3    0.841  0.0460        0.756        0.937\n    8     51       2    0.810  0.0495        0.718        0.913\n    9     50       1    0.794  0.0510        0.700        0.900\n   10     49       1    0.778  0.0524        0.682        0.888\n\n                allo=Conv, sex=F \n time n.risk n.event survival std.err lower 95% CI upper 95% CI\n    0     24       0    1.000  0.0000        1.000        1.000\n    1     24       0    1.000  0.0000        1.000        1.000\n    2     24       0    1.000  0.0000        1.000        1.000\n    3     23       1    0.958  0.0408        0.882        1.000\n    4     23       0    0.958  0.0408        0.882        1.000\n    5     23       0    0.958  0.0408        0.882        1.000\n    6     22       1    0.917  0.0564        0.813        1.000\n    7     20       2    0.833  0.0761        0.697        0.997\n    8     19       1    0.792  0.0829        0.645        0.972\n    9     17       2    0.708  0.0928        0.548        0.916\n   10     15       2    0.625  0.0988        0.458        0.852\n\n                allo=Conv, sex=M \n time n.risk n.event survival std.err lower 95% CI upper 95% CI\n    0     56       0    1.000  0.0000        1.000        1.000\n    1     56       0    1.000  0.0000        1.000        1.000\n    2     56       0    1.000  0.0000        1.000        1.000\n    3     55       1    0.982  0.0177        0.948        1.000\n    4     55       0    0.982  0.0177        0.948        1.000\n    5     50       5    0.893  0.0413        0.815        0.978\n    6     48       2    0.857  0.0468        0.770        0.954\n    7     47       1    0.839  0.0491        0.748        0.941\n    8     46       1    0.821  0.0512        0.727        0.928\n    9     44       2    0.786  0.0548        0.685        0.901\n   10     38       6    0.679  0.0624        0.567        0.813\n```\n\n\n:::\n:::\n\nHere we can see that after 10 years, there is already a lower survival probability for the conventional treatment group. And for females, it seems. But that highly depends on the intervention group.\n\nBut it is much better to visualize it with a kaplan meier plot, to really see the differences, and when - in terms of time since baseline - does the survival differ.\n\nShown below are plots for each of the different fits mentioned above, showing the overall survival modelel, differences in survival between intervention groups for both sexes, and ditto, but subset for each sex.\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# Function to save some space\nsurvplot_function <- function(fit,data){\n  out <- ggsurvplot(\n    fit, data = data,\n    conf.int = TRUE,\n    risk.table = TRUE,\n    palette = \"dark2\",\n    xlab = NULL, ylab = \"Survival Probability\",\n    title = \"Kaplan Meier Estimator for survival probability, in years\"\n    )\n\n  return(out)\n}\n\n# Overall\nsurvplot_function(km_os,steno2)\n```\n\n::: {.cell-output-display}\n![](index_files/figure-html/survplot KM-1.png){width=768}\n:::\n\n```{.r .cell-code}\n# allo\nsurvplot_function(km_allo,steno2)\n```\n\n::: {.cell-output-display}\n![](index_files/figure-html/survplot KM-2.png){width=768}\n:::\n\n```{.r .cell-code}\n# sex\nsurvplot_function(km_sex,steno2)\n```\n\n::: {.cell-output-display}\n![](index_files/figure-html/survplot KM-3.png){width=768}\n:::\n\n```{.r .cell-code}\n# allo sex\nsurvplot_function(km_allo_sex,steno2)\n```\n\n::: {.cell-output-display}\n![](index_files/figure-html/survplot KM-4.png){width=768}\n:::\n:::\n\n\nThats a bit rough to look at, but provides plenty of information:\n\n1. intervention group has higher survival probability\n2. female sex seems to indicate having the highest survival probability, at least in intervention group\n3. frequently overlapping confidence intervals, low probability of actual difference atleast in the first 10 years where most of the overlap occurs\n\nFor the second point, the lines cross twice, either because of the lower number of females or because of some unknown factor. When the lines cross its difficult to say whether there is any consistent survival difference with certainty.\n\nBut let's try to make it pretty - just with the help of the `survminer` package help - accessed in Rstudio via `?ggsurvplot`.\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# allo\nsurv_p_allo_pretty <- ggsurvplot(\n  fit = km_allo, data = steno2,\n  surv.median.line = \"hv\", # Add medians survival\n  legend.title = \"Allocation group\",\n  legend.labs = c(\"Intervention\", \"Conventional\"),\n  pval = TRUE,\n  conf.int = TRUE,\n\n  risk.table = TRUE,\n  tables.height = 0.2,\n  tables.theme = theme(axis.title.y = element_blank()),\n\n  palette = \"dark2\",\n  ggtheme = theme_bw(),\n  xlab = NULL, ylab = \"Survival Probability\",\n  title = \"Kaplan Meier Estimator for survival probability, in years\"\n  )\n\nsurv_p_allo_sex_pretty <- ggsurvplot(\n  fit = km_allo_sex, data = steno2,\n  surv.median.line = \"hv\", # Add medians survival\n  legend.title = \"Allocation group, Sex\",\n  legend.labs = c(\"Int, F\", \"Int, M\", \"Conv, F\", \"Conv, M\"),\n  conf.int = TRUE,\n\n  risk.table = TRUE,\n  tables.height = 0.2,\n  tables.theme = theme(axis.title.y = element_blank()),\n\n  palette = \"dark2\",\n  ggtheme = theme_bw(),\n  xlab = NULL, ylab = \"Survival Probability\",\n  title = \"Kaplan Meier Estimator for survival probability, in years\"\n  )\n```\n\n::: {.cell-output .cell-output-stderr}\n\n```\nWarning in geom_segment(aes(x = 0, y = max(y2), xend = max(x1), yend = max(y2)), : All aesthetics have length 1, but the data has 3 rows.\nℹ Please consider using `annotate()` or provide this layer with data containing\n  a single row.\n```\n\n\n:::\n\n```{.r .cell-code}\nsurv_p_allo_pretty\n```\n\n::: {.cell-output-display}\n![](index_files/figure-html/survplot KM pretty, fewer-1.png){width=768}\n:::\n\n```{.r .cell-code}\nsurv_p_allo_sex_pretty\n```\n\n::: {.cell-output .cell-output-stderr}\n\n```\nWarning in geom_segment(aes(x = 0, y = max(y2), xend = max(x1), yend = max(y2)), : All aesthetics have length 1, but the data has 3 rows.\nℹ Please consider using `annotate()` or provide this layer with data containing\n  a single row.\nAll aesthetics have length 1, but the data has 3 rows.\nℹ Please consider using `annotate()` or provide this layer with data containing\n  a single row.\nAll aesthetics have length 1, but the data has 3 rows.\nℹ Please consider using `annotate()` or provide this layer with data containing\n  a single row.\n```\n\n\n:::\n\n::: {.cell-output-display}\n![](index_files/figure-html/survplot KM pretty, fewer-2.png){width=768}\n:::\n:::\n\nNow slightly cleaned up, and with some median survival lines - the follow-up time at which 50 has experienced the event - added.\n\n##### Test of differences\n\nOne way of testing the differences between two survival curves is the log-rank test. Although, as far as I remember, its not given much weight - especially compared to visual inspection coupled with careful thinking and analysis of the different factors that play into a survival analysis.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nsurvdiff(Surv(time_yrs, event_num) ~ allo, data = steno2)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nCall:\nsurvdiff(formula = Surv(time_yrs, event_num) ~ allo, data = steno2)\n\n           N Observed Expected (O-E)^2/E (O-E)^2/V\nallo=Int  80       38     51.7      3.64      8.29\nallo=Conv 80       55     41.3      4.56      8.29\n\n Chisq= 8.3  on 1 degrees of freedom, p= 0.004 \n```\n\n\n:::\n\n```{.r .cell-code}\nsurvdiff(Surv(time_yrs, event_num) ~ sex, data = steno2)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nCall:\nsurvdiff(formula = Surv(time_yrs, event_num) ~ sex, data = steno2)\n\n        N Observed Expected (O-E)^2/E (O-E)^2/V\nsex=F  41       20     25.5     1.182      1.63\nsex=M 119       73     67.5     0.446      1.63\n\n Chisq= 1.6  on 1 degrees of freedom, p= 0.2 \n```\n\n\n:::\n:::\n\n\nSeems there is a statistically significant difference between allocation groups and not sex. Kinda what I expected from the reading of the plots.\n\nI have forgotten how to interpret the log-rank model for a fit with two different binary variables, so I will refrain from attempting that at the moment.\n\n\n#### Cox model\n\nNow we enter the part of survival analysis where we want to see what effect sizes the different predictors have on the outcome.\n\nAs mentioned in @sec-output-model-disclaimer, I am not a statistician, and I do not think the target audience of 0 to 1/3 of a person should be a statistician, so I will not bombard You with all the equations and definitions of survival analysis, such as $S(t) = P(T>t) = etc..etc$.\n\nI will just try to write in plain terms.\n\nWhere the survival function derived from the Kaplan Meier Estimator up above could tell us how many people have survived at time $t$, and the difference between groups, the cox proportional hazards model can describe the relative difference in effect between different predictors, in regards to the risk of the outcome.\n\nSpoken plainly: the cox proportional hazards model can tell us something about how much the risk of the outcome, `doDth`, increases or decreases, for those in one group compared to another group. And then if there are multiple variables in the analysis, its assumed all other variables stay the same.\n\nLet's do the same models as for the survival function.\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# Overall, by treatment allocation, subset into sex\ncox_allo <- coxph(Surv(time_yrs, event_num) ~ allo, data = steno2)\ncox_sex <- coxph(Surv(time_yrs, event_num) ~ sex, data = steno2)\ncox_allo_sex <- coxph(Surv(time_yrs, event_num) ~ allo + sex, data = steno2)\n```\n:::\n\n\n##### Checking models out before interpreting estimates\n\nBefore we go ahead and interpret estimates, it is recommended that you see how the data fits with the assumptions that are necessary for the cox model to be interpreted correctly.\n\nIn general, I have been taught to test the cox proportional hazards assumption, which can be done in two ways:\n\n- plot observed survival curves in the two groups with estimated survival curves from the model\n- log log plot of two survival curves\n\n\n::: {.cell}\n\n```{.r .cell-code}\nplot(km_allo,\n     col=1:2,\n     lty=2,\n     main='Observed and fitted survival')\nlines(survfit(cox_allo,\n              newdata=data.frame(allo=c('Int','Conv'))),\n      col=1:2)\nlegend('bottomleft',\n       lty=rep(1:2,2),col=rep(1:2,each=2),\n       legend=c('Int, fit','Int, obs','Conv, fit','Conv, obs'))\n```\n\n::: {.cell-output-display}\n![](index_files/figure-html/observed versus estimated, loglog plot-1.png){width=768}\n:::\n\n```{.r .cell-code}\nplot(km_allo,\n     col=1:2,\n     fun='cloglog',\n     main='Log-log plot')\nlegend('topleft',lty=rep(1,2),col=1:2,legend=levels(steno2$allo))\n```\n\n::: {.cell-output-display}\n![](index_files/figure-html/observed versus estimated, loglog plot-2.png){width=768}\n:::\n:::\n\n\nHmm. I also wanted to use `ggsurvplot` but for some reason, I can only get the old code, without risk table, from my course long ago in basic biostats to work, so I will use that.\n\n**But more importantly:**\n\nBasically what we can see from the two above plots is that the proportional hazards assumption doesn't hold well, due to crossover of survival curves and perhaps a slight possibility of different baseline hazards.\n\nIf the hazards for the groups being compared are not relatively proportional over time, its estimates do not precisely answer the question of \"how much more risk is one group in of the outcome versus the other\", since it varies over time.\n\nIt answers a general tendency, which might switch at some point in the data, as can be seen by earlier plots where observed survival curves overlap early.\n\n##### Estimates\n\nBut lets still look at the model estimates and interpret them a bit, but bearing in mind that the proportional hazards assumption doesn't hold.\n\nFor a more simple output of the models, I use `broom::tidy()`.\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# list\ncox_models <- list(cox_allo,cox_sex,cox_allo_sex)\nnames(cox_models) <- paste0(\"model_\", seq_along(cox_models))\n\n# tidy\ntidy_cox_models <- map_dfr(cox_models, ~broom::tidy(.x, conf.int = TRUE))\ntidy_cox_models\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n# A tibble: 4 × 7\n  term     estimate std.error statistic p.value conf.low conf.high\n  <chr>       <dbl>     <dbl>     <dbl>   <dbl>    <dbl>     <dbl>\n1 alloConv    0.602     0.212      2.84 0.00455    0.186     1.02 \n2 sexM        0.321     0.253      1.27 0.203     -0.174     0.816\n3 alloConv    0.628     0.213      2.95 0.00316    0.211     1.05 \n4 sexM        0.379     0.253      1.50 0.135     -0.118     0.875\n```\n\n\n:::\n\n```{.r .cell-code}\ntidy_cox_models_exp <- map_dfr(cox_models, ~broom::tidy(.x, conf.int = TRUE, exponentiate = TRUE))\ntidy_cox_models_exp\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n# A tibble: 4 × 7\n  term     estimate std.error statistic p.value conf.low conf.high\n  <chr>       <dbl>     <dbl>     <dbl>   <dbl>    <dbl>     <dbl>\n1 alloConv     1.83     0.212      2.84 0.00455    1.20       2.77\n2 sexM         1.38     0.253      1.27 0.203      0.840      2.26\n3 alloConv     1.87     0.213      2.95 0.00316    1.23       2.84\n4 sexM         1.46     0.253      1.50 0.135      0.889      2.40\n```\n\n\n:::\n:::\n\n\nWhere the first two rows are the first two models, and row three to four is the model with both variables, so you can see how much of an effect it has if you include them both.\n\nLet's go ahead and do a simple interpretation on the model with both allocation and sex as predictors.\n\nUsing `broom::augment`, one can plop the estimates into a table as an overview of what the model estimates mean for each variable.\n\n\n::: {.cell}\n\n```{.r .cell-code}\ncox_grid_1 <- expand.grid(allo = c(\"Conv\", \"Int\"))\ncox_grid_2 <- expand.grid(allo = c(\"Conv\", \"Int\"), sex = c(\"M\",\"F\"))\n(broom::augment(cox_allo,newdata = cox_grid_1, type.predict = \"risk\"))\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n# A tibble: 2 × 3\n  allo  .fitted .se.fit\n  <fct>   <dbl>   <dbl>\n1 Conv     1.83   0.287\n2 Int      1      0    \n```\n\n\n:::\n\n```{.r .cell-code}\n(broom::augment(cox_allo_sex,newdata = cox_grid_2, type.predict = \"risk\"))\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n# A tibble: 4 × 4\n  allo  sex   .fitted .se.fit\n  <fct> <fct>   <dbl>   <dbl>\n1 Conv  M        2.74   0.567\n2 Int   M        1.46   0.306\n3 Conv  F        1.87   0.291\n4 Int   F        1      0    \n```\n\n\n:::\n:::\n\n\nDue to the `type.predict` option, the result is exponentiated so it can be interpreted as risk increase.\n\nSo, the model output for `cox_allo_sex` can be interpreted in the following way:\n\nFemales on intervention treatment are the reference group, and females with conventional treatment have 87% higher risk of death, while males on intervention treatment have 46%, and males on conventional 174% higher risk.\n\n\n## Summary / cleaned up / refactored\n\n\n::: {.cell}\n::: {.cell-output .cell-output-stdout}\n\n```\nRows: 160\nColumns: 14\n$ id       <dbl> 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18…\n$ allo     <fct> Int, Int, Conv, Conv, Conv, Conv, Conv, Int, Int, Int, Int, C…\n$ sex      <fct> M, M, M, M, M, M, F, M, M, M, M, M, M, M, F, M, F, F, M, M, F…\n$ baseCVD  <dbl> 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 1, 0, 0, 0, 1, 0, 0, 0, 0, 0…\n$ deathCVD <dbl> 0, 0, 0, 0, 1, 0, 0, 0, 1, 0, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0…\n$ doBth    <date> 1932-04-11, 1946-11-09, 1943-06-07, 1944-11-01, 1935-12-22, …\n$ doDM     <date> 1991-01-21, 1982-01-30, 1982-07-17, 1976-10-28, 1986-05-06, …\n$ doBase   <date> 1993-04-30, 1993-06-08, 1993-05-17, 1993-05-04, 1993-03-23, …\n$ doCVD1   <date> 2014-05-24, 2009-03-15, 2001-08-28, 1995-05-31, 1993-12-16, …\n$ doCVD2   <date> NA, 2009-07-02, NA, 1997-06-26, 1994-08-05, NA, 2006-02-27, …\n$ doCVD3   <date> NA, 2010-02-16, NA, 2003-06-17, 1997-12-25, NA, NA, NA, NA, …\n$ doESRD   <date> NaN, NaN, NaN, NaN, 1998-02-18, 2014-07-07, NaN, 2009-03-06,…\n$ doEnd    <date> 2014-10-12, 2014-08-04, 2001-08-21, 2003-06-11, 1998-01-18, …\n$ doDth    <date> NA, NA, 2001-09-20, 2003-06-24, 1998-02-25, NA, 2006-04-24, …\nRows: 750\nColumns: 5\n$ id   <dbl> 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19…\n$ doV  <date> 1993-05-07, 1993-05-05, 1993-05-11, 1993-05-12, 1993-02-25, 1993…\n$ a1c  <dbl> 87.3, 66.5, 73.0, 61.2, 102.7, 93.4, 94.5, 103.9, 46.4, 84.4, 47.…\n$ chol <dbl> 3.9, 6.6, 5.6, 5.2, 6.0, 4.8, 8.6, 5.1, 4.2, 5.4, 8.9, 5.3, 6.0, …\n$ crea <dbl> 83, 83, 68, 97, 149, 55, 56, 78, 123, 79, 74, 84, 65, 52, 61, 61,…\nRows: 563\nColumns: 3\n$ id    <dbl> 1, 1, 1, 1, 1, 2, 2, 2, 2, 2, 3, 3, 3, 4, 4, 4, 5, 5, 6, 6, 6, 6…\n$ doTr  <date> 1993-06-12, 1995-05-13, 2000-01-26, 2001-12-26, 2007-04-27, 199…\n$ state <fct> Mic, Norm, Mic, Norm, Mic, Norm, Mic, Mac, Mic, Mic, Mic, Mic, M…\n```\n\n\n:::\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[[1]]\n     id allo sex baseCVD deathCVD      doBth       doDM     doBase     doCVD1\n1     1  Int   M       0        0 1932-04-11 1991-01-21 1993-04-30 2014-05-24\n2     2  Int   M       0        0 1946-11-09 1982-01-30 1993-06-08 2009-03-15\n3     3 Conv   M       0        0 1943-06-07 1982-07-17 1993-05-17 2001-08-28\n4     4 Conv   M       0        0 1944-11-01 1976-10-28 1993-05-04 1995-05-31\n5     5 Conv   M       0        1 1935-12-22 1986-05-06 1993-03-23 1993-12-16\n6     6 Conv   M       1        0 1946-12-23 1986-06-03 1993-03-31 1998-10-21\n7     7 Conv   F       0        0 1929-02-17 1977-12-18 1993-03-28 2000-12-27\n8     8  Int   M       0        0 1932-10-30 1982-10-26 1993-04-10 2011-11-16\n9     9  Int   M       0        1 1930-06-26 1962-06-21 1993-03-22 1995-01-21\n10   10  Int   M       0        0 1937-06-28 1983-01-24 1993-01-09 2011-05-23\n11   11  Int   M       0        1 1930-02-08 1991-10-27 1993-02-11 2005-08-27\n12   12 Conv   M       1        1 1928-04-03 1981-05-12 1993-03-11 1993-12-14\n13   13  Int   M       0        0 1945-09-07 1990-03-23 1993-03-01       <NA>\n14   14  Int   M       0        0 1929-10-08 1981-03-26 1993-02-10 2014-02-09\n15   15  Int   F       0        0 1936-03-29 1988-06-10 1993-01-05       <NA>\n16   16  Int   M       1        0 1934-12-14 1987-07-18 1993-01-19 2000-01-20\n17   17  Int   F       0        0 1942-12-16 1984-10-27 1993-06-11       <NA>\n18   18 Conv   F       0        0 1939-04-11 1966-06-11 1993-06-08 1998-04-05\n19   19 Conv   M       0        0 1945-12-29 1992-10-21 1993-06-02       <NA>\n20   20 Conv   M       0        0 1946-05-08 1988-07-27 1993-06-07       <NA>\n21   21 Conv   F       0        0 1935-09-16 1981-11-03 1993-06-11 1994-05-05\n22   22  Int   F       0        0 1933-07-13 1975-08-11 1993-05-16       <NA>\n23   23 Conv   M       0        1 1934-06-19 1980-02-22 1993-01-12 1993-03-17\n24   24  Int   M       0        0 1937-06-16 1989-08-04 1993-03-11 2005-05-28\n25   25 Conv   M       0        0 1935-09-04 1991-01-17 1993-04-04       <NA>\n26   26 Conv   M       0        1 1929-08-18 1990-03-17 1993-04-09 1999-09-18\n27   27 Conv   M       0        0 1931-03-02 1983-02-17 1993-04-16 2002-07-29\n28   28  Int   M       0        0 1945-09-26 1990-03-14 1993-03-13       <NA>\n29   29 Conv   M       0        1 1939-03-11 1969-08-03 1993-03-26 2005-02-22\n30   30  Int   M       1        0 1932-07-09 1982-05-02 1993-05-03 2004-05-04\n31   31 Conv   F       0        1 1942-06-30 1986-04-29 1993-03-12 2006-02-26\n32   32 Conv   F       0        0 1944-10-25 1991-10-01 1993-03-21 2000-02-23\n33   33  Int   M       0        0 1941-05-03 1988-10-14 1993-03-16       <NA>\n34   34  Int   M       0        0 1941-10-30 1990-02-07 1993-02-28 1996-01-06\n35   35 Conv   F       0        1 1928-08-29 1991-09-19 1993-06-30 2001-08-23\n36   36 Conv   F       1        0 1947-02-12 1964-02-07 1993-04-14 2001-12-02\n37   37  Int   M       0        0 1948-02-01 1987-03-27 1993-01-24 2008-09-28\n38   38 Conv   M       0        1 1932-06-14 1986-10-14 1993-03-07 1998-09-05\n39   39  Int   M       0        0 1944-06-23 1985-07-10 1993-01-20 2010-10-27\n40   40 Conv   F       0        1 1937-12-12 1984-08-12 1993-04-02 1997-09-08\n41   41  Int   M       0        0 1928-11-12 1991-06-28 1992-12-29 2002-06-26\n42   42 Conv   M       0        1 1936-02-03 1974-11-23 1993-03-12 2002-10-01\n43   43 Conv   M       1        0 1930-08-28 1979-03-04 1993-01-14 1994-01-29\n44   44 Conv   M       1        0 1948-06-14 1985-04-28 1993-02-23       <NA>\n45   45 Conv   M       0        0 1945-08-27 1990-11-01 1993-02-28 2010-03-17\n46   47 Conv   F       0        0 1937-05-25 1974-12-14 1993-04-30 1997-05-15\n47   48 Conv   F       0        0 1926-09-12 1984-07-19 1993-06-24 2010-11-04\n48   50 Conv   M       0        1 1929-12-21 1993-04-18 1993-05-28 2002-07-06\n49   51  Int   M       0        0 1946-05-20 1981-09-04 1993-06-04 2010-07-20\n50   52  Int   M       0        0 1944-07-14 1989-07-01 1993-02-03 1996-12-01\n51   53 Conv   F       0        0 1927-06-17 1982-07-04 1993-03-05 1996-12-16\n52   54  Int   F       1        0 1945-04-26 1989-06-21 1993-02-26       <NA>\n53   55  Int   F       0        0 1948-04-10 1987-05-13 1993-04-15       <NA>\n54   56  Int   M       0        0 1932-09-16 1989-03-06 1993-03-11 2012-04-16\n55   57 Conv   F       0        0 1928-11-22 1974-02-16 1993-02-05 1995-08-17\n56   58 Conv   M       0        0 1938-03-11 1987-08-26 1993-02-04 2005-05-22\n57   59  Int   M       0        0 1929-04-17 1985-10-31 1993-07-02 2004-10-19\n58   60  Int   M       0        1 1936-02-27 1986-04-05 1993-06-24 1997-09-22\n59   61 Conv   M       0        0 1941-06-28 1986-08-29 1993-05-16       <NA>\n60   62 Conv   F       0        1 1935-01-09 1985-07-16 1993-06-22 1999-04-06\n61   63 Conv   M       0        1 1931-10-21 1987-07-25 1993-04-04 1999-01-01\n62   64 Conv   M       0        0 1944-06-07 1990-01-01 1993-03-19 2006-10-22\n63   65  Int   F       0        0 1946-01-30 1975-02-02 1993-05-05       <NA>\n64   66 Conv   M       0        1 1932-10-14 1979-09-30 1993-03-01 1995-12-23\n65   67  Int   F       0        0 1927-08-15 1978-08-23 1993-05-11 1994-02-11\n66   68  Int   M       0        0 1947-06-18 1989-10-11 1993-03-30 2000-10-09\n67   69  Int   M       0        0 1933-01-08 1991-11-08 1993-03-04       <NA>\n68   70 Conv   M       0        0 1934-10-24 1978-10-12 1993-01-25 1995-03-26\n69   71 Conv   M       0        0 1937-03-10 1982-05-14 1993-05-18 2004-08-21\n70   72 Conv   M       0        0 1947-10-27 1990-09-03 1993-05-03       <NA>\n71   73  Int   M       0        0 1930-04-17 1977-02-16 1993-01-22 1997-01-29\n72   74  Int   F       1        0 1928-08-14 1974-05-16 1993-05-12 1997-03-06\n73   75 Conv   F       0        1 1935-03-04 1981-01-21 1993-03-19 2008-11-21\n74   76  Int   M       0        0 1936-06-29 1980-04-16 1993-02-17 1996-09-05\n75   77  Int   M       0        0 1938-04-03 1991-10-10 1993-03-23       <NA>\n76   78 Conv   M       0        0 1928-05-30 1985-07-21 1993-04-08       <NA>\n77   79  Int   M       0        1 1931-12-03 1974-02-14 1993-04-07 1994-10-31\n78   80 Conv   M       0        0 1940-07-03 1990-03-22 1993-04-04 2008-05-21\n79   81  Int   M       0        1 1943-12-17 1990-03-22 1993-03-21 1999-12-18\n80   82  Int   M       1        0 1927-09-07 1990-10-13 1993-01-02 1999-02-24\n81   83  Int   M       0        1 1930-12-23 1989-06-28 1992-12-22 1994-12-04\n82   84  Int   F       0        0 1932-07-21 1983-11-16 1993-03-29 2009-04-03\n83   85 Conv   M       0        0 1943-05-22 1987-04-22 1993-03-31 2009-09-26\n84   86  Int   F       0        0 1932-11-18 1973-04-09 1993-06-01       <NA>\n85   87  Int   M       0        1 1933-03-21 1984-06-25 1993-04-20 1993-10-17\n86   88 Conv   M       0        0 1942-01-13 1986-05-16 1993-02-15 1998-01-18\n87   89  Int   M       1        0 1935-08-18 1992-06-30 1993-06-30 1995-05-20\n88   90 Conv   M       0        1 1947-01-22 1988-10-16 1993-07-27 2001-07-03\n89   91  Int   M       0        0 1930-10-24 1990-03-02 1993-08-23 2001-08-05\n90   92  Int   M       1        0 1946-03-10 1992-09-02 1993-08-25       <NA>\n91   93 Conv   M       0        0 1951-05-04 1980-07-10 1993-08-20 1998-08-22\n92   94 Conv   M       0        1 1940-03-21 1993-05-14 1993-07-19 2007-09-24\n93   95  Int   M       0        0 1938-01-14 1992-02-25 1993-09-01 2004-03-20\n94   96  Int   M       0        1 1942-02-13 1988-05-17 1993-08-26 1998-12-31\n95   97  Int   F       0        0 1946-05-12 1992-12-19 1993-08-24       <NA>\n96   98  Int   M       0        1 1933-09-20 1975-08-29 1993-08-27 1997-05-04\n97  100  Int   M       1        0 1949-11-13 1985-12-15 1993-09-10       <NA>\n98  101  Int   M       0        0 1936-06-03 1988-12-28 1994-02-07       <NA>\n99  102  Int   M       0        1 1935-04-09 1990-03-19 1993-07-17 1995-04-23\n100 103  Int   M       0        0 1932-10-18 1981-07-20 1993-08-28       <NA>\n101 104  Int   M       0        0 1946-12-12 1986-02-02 1993-07-22 2014-05-30\n102 105  Int   M       1        0 1949-01-14 1993-12-06 1994-01-15       <NA>\n103 107  Int   F       0        0 1936-07-26 1992-04-10 1993-09-01 2001-06-30\n104 108  Int   M       0        0 1956-04-07 1992-05-20 1993-08-28       <NA>\n105 110  Int   M       0        0 1934-07-13 1989-01-27 1993-09-14 2009-12-09\n106 111  Int   M       0        0 1951-05-15 1993-05-30 1993-08-16       <NA>\n107 112 Conv   F       0        0 1949-01-18 1988-09-06 1993-11-02       <NA>\n108 113 Conv   F       0        0 1931-05-19 1966-10-24 1993-10-05 1999-02-17\n109 114 Conv   M       0        0 1934-07-21 1982-11-05 1993-10-02 1998-06-01\n110 115 Conv   M       0        0 1940-11-12 1984-05-15 1993-10-30       <NA>\n111 116 Conv   M       0        1 1928-09-06 1987-05-12 1993-09-12 1998-07-22\n112 118 Conv   M       1        1 1933-09-07 1988-10-20 1993-10-09 2006-04-18\n113 119 Conv   M       0        0 1949-08-17 1993-03-07 1993-09-14 1998-02-28\n114 120 Conv   M       0        0 1939-04-06 1984-01-23 1993-10-27 1996-06-20\n115 121 Conv   M       1        0 1927-04-30 1978-01-22 1993-11-16 1997-01-28\n116 123  Int   M       0        0 1948-03-02 1991-01-13 1993-10-10 2013-02-04\n117 126  Int   F       0        0 1934-07-27 1986-06-28 1993-10-21       <NA>\n118 128 Conv   M       0        0 1937-03-14 1989-02-16 1993-10-03 1995-11-13\n119 129 Conv   M       0        1 1936-06-24 1988-07-23 1993-10-17 2002-11-20\n120 130 Conv   M       0        1 1939-07-01 1980-11-23 1993-10-15 1996-01-16\n121 131 Conv   M       1        0 1931-10-07 1992-02-15 1993-11-27 2003-12-18\n122 133  Int   M       0        0 1945-08-12 1992-09-24 1994-02-21 2007-12-24\n123 134 Conv   F       0        1 1930-01-31 1980-08-28 1993-11-14 1994-12-01\n124 135 Conv   F       0        0 1931-07-05 1993-04-16 1993-10-12 1997-06-05\n125 136 Conv   M       0        0 1949-10-23 1983-03-15 1993-12-16 2000-06-12\n126 137 Conv   M       0        0 1932-09-11 1993-09-04 1993-10-31 1998-09-07\n127 138 Conv   F       0        0 1947-10-05 1993-04-24 1993-12-14       <NA>\n128 139 Conv   M       0        0 1949-05-08 1988-12-30 1993-11-22 1995-07-14\n129 140 Conv   M       1        0 1951-04-14 1987-08-10 1993-11-28 2001-04-03\n130 142  Int   M       0        0 1942-05-15 1989-06-26 1993-12-03 2007-09-04\n131 143  Int   M       0        0 1936-10-31 1985-11-01 1993-12-12 2002-05-30\n132 144 Conv   M       1        0 1932-11-21 1987-04-20 1993-12-19 2001-05-17\n133 145  Int   M       0        1 1936-11-21 1985-12-17 1994-02-01 1999-04-25\n134 146 Conv   M       0        1 1944-05-25 1983-11-18 1994-01-31 1994-07-17\n135 147  Int   M       1        0 1945-02-16 1994-01-04 1994-01-04 2012-08-25\n136 148 Conv   F       0        0 1938-12-29 1986-04-07 1993-12-26 2012-06-20\n137 150 Conv   F       0        0 1946-02-18 1989-10-29 1993-12-24       <NA>\n138 151 Conv   M       0        1 1929-02-04 1988-05-12 1994-01-25 2004-02-28\n139 152  Int   F       1        0 1947-11-08 1993-06-08 1994-01-13 2009-04-09\n140 153  Int   M       0        0 1934-10-31 1985-04-01 1994-02-17 1995-09-22\n141 155 Conv   M       0        0 1949-11-21 1994-02-07 1994-02-12       <NA>\n142 156  Int   M       0        0 1942-09-10 1993-05-13 1994-02-10 2002-04-25\n143 157 Conv   M       0        1 1938-03-08 1987-05-24 1994-02-27 2007-07-03\n144 158  Int   M       1        0 1931-06-17 1986-09-07 1994-01-22 2009-12-10\n145 159  Int   M       0        1 1926-07-13 1990-10-20 1994-01-10 2010-06-08\n146 160 Conv   M       0        0 1928-06-20 1986-12-03 1994-02-02 1994-12-13\n147 161  Int   M       0        0 1939-03-16 1989-11-10 1994-02-25       <NA>\n148 163  Int   M       0        0 1929-12-31 1990-11-12 1994-01-24 2002-02-17\n149 165 Conv   F       0        0 1930-08-16 1992-09-29 1994-02-21 2002-04-04\n150 166 Conv   M       0        1 1936-09-03 1986-08-23 1994-01-25 2007-04-19\n151 167  Int   F       0        0 1952-11-12 1980-07-07 1994-03-09       <NA>\n152 168 Conv   M       0        0 1937-05-19 1986-03-12 1994-02-13 2002-03-10\n153 169  Int   M       0        0 1946-10-08 1993-09-03 1994-05-12       <NA>\n154 170  Int   F       0        0 1933-04-02 1991-10-24 1994-05-19       <NA>\n155 171  Int   M       0        0 1939-07-02 1992-09-22 1994-04-23       <NA>\n156 172 Conv   F       0        0 1950-11-23 1983-09-27 1994-05-05 2011-12-25\n157 173  Int   F       0        0 1943-10-29 1982-07-03 1994-05-19       <NA>\n158 174  Int   M       0        0 1931-10-27 1989-04-01 1994-06-14       <NA>\n159 175  Int   M       0        0 1936-12-26 1991-12-17 1994-05-06 1998-10-01\n160 176 Conv   F       0        0 1943-02-12 1987-10-23 1994-05-25       <NA>\n        doCVD2     doCVD3     doESRD      doEnd      doDth\n1         <NA>       <NA>        NaN 2014-10-12       <NA>\n2   2009-07-02 2010-02-16        NaN 2014-08-04       <NA>\n3         <NA>       <NA>        NaN 2001-08-21 2001-09-20\n4   1997-06-26 2003-06-17        NaN 2003-06-11 2003-06-24\n5   1994-08-05 1997-12-25 1998-02-18 1998-01-18 1998-02-25\n6         <NA>       <NA> 2014-07-07 2014-09-07       <NA>\n7   2006-02-27       <NA>        NaN 2006-03-28 2006-04-24\n8   2012-02-12       <NA> 2009-03-06 2012-02-25 2012-02-27\n9   1995-11-25       <NA>        NaN 1995-12-14 1995-12-05\n10        <NA>       <NA>        NaN 2011-05-28 2011-05-30\n11  2006-01-23       <NA> 2006-01-11 2006-01-26 2006-02-03\n12  1995-04-27 2002-05-16        NaN 2002-09-28 2002-09-15\n13        <NA>       <NA>        NaN 2014-09-25       <NA>\n14        <NA>       <NA>        NaN 2014-01-15 2014-02-16\n15        <NA>       <NA>        NaN 2014-12-01       <NA>\n16  2002-03-05 2009-08-30        NaN 2009-09-05 2009-09-07\n17        <NA>       <NA>        NaN 2014-11-01       <NA>\n18  1998-06-11 1998-08-20        NaN 2014-12-30       <NA>\n19        <NA>       <NA>        NaN 2014-12-30       <NA>\n20        <NA>       <NA>        NaN 2014-09-02       <NA>\n21        <NA>       <NA>        NaN 2014-10-16       <NA>\n22        <NA>       <NA>        NaN 2014-10-13       <NA>\n23  1998-12-22       <NA>        NaN 1998-12-30 1998-12-29\n24  2007-09-07 2010-03-02        NaN 2010-02-26 2010-03-09\n25        <NA>       <NA>        NaN 2014-08-14       <NA>\n26  2000-01-20 2001-11-09        NaN 2001-11-09 2001-11-16\n27  2006-02-15 2006-05-07        NaN 2009-03-25 2009-03-17\n28        <NA>       <NA>        NaN 2014-08-06       <NA>\n29        <NA>       <NA>        NaN 2005-03-22 2005-03-23\n30  2005-08-11       <NA>        NaN 2005-07-18 2005-08-22\n31  2007-04-04 2008-07-03        NaN 2010-05-06 2010-04-21\n32        <NA>       <NA>        NaN 2000-03-03 2000-03-01\n33        <NA>       <NA>        NaN 2014-11-01       <NA>\n34  2005-05-28 2012-07-21        NaN 2014-09-29       <NA>\n35  2002-11-01 2002-12-14 2003-10-23 2005-02-02 2005-03-09\n36        <NA>       <NA>        NaN 2014-11-26       <NA>\n37        <NA>       <NA>        NaN 2008-09-12 2008-10-05\n38  2000-03-22 2000-05-08        NaN 2003-04-28 2003-04-17\n39        <NA>       <NA>        NaN 2014-08-27       <NA>\n40  2000-01-13 2000-02-04        NaN 2000-01-05 2000-02-11\n41        <NA>       <NA>        NaN 2002-06-21 2002-07-18\n42  2002-12-05 2004-12-13        NaN 2005-11-02 2005-11-03\n43  2002-03-08 2002-06-10        NaN 2002-05-14 2002-06-17\n44        <NA>       <NA>        NaN 2014-08-14       <NA>\n45        <NA>       <NA>        NaN 2014-09-29       <NA>\n46  2001-10-08 2001-12-07        NaN 2002-07-09 2002-07-09\n47        <NA>       <NA>        NaN 2010-10-16 2010-11-11\n48  2002-07-28       <NA>        NaN 2002-08-10 2002-09-11\n49  2011-03-04       <NA>        NaN 2014-10-08       <NA>\n50  2006-06-05 2006-10-01        NaN 2014-09-01       <NA>\n51  2001-11-28 2002-03-08        NaN 2002-02-22 2002-03-15\n52        <NA>       <NA>        NaN 2014-09-24       <NA>\n53        <NA>       <NA>        NaN 2014-08-07       <NA>\n54  2012-04-22       <NA> 2008-05-08 2012-04-21 2012-05-20\n55  1996-01-27 2000-04-15        NaN 2000-03-23 2000-04-22\n56        <NA>       <NA>        NaN 2005-05-22 2005-06-17\n57        <NA>       <NA>        NaN 2004-09-20 2004-10-26\n58  1997-12-26       <NA>        NaN 1997-12-09 1998-01-02\n59        <NA>       <NA>        NaN 2014-11-01       <NA>\n60  2003-01-04 2004-04-09        NaN 2009-12-23 2010-01-18\n61  1999-02-21 2000-10-11        NaN 2000-09-28 2000-10-18\n62        <NA>       <NA>        NaN 2006-10-14 2006-10-29\n63        <NA>       <NA>        NaN 2014-12-30       <NA>\n64  1996-02-05       <NA>        NaN 1996-01-17 1996-02-12\n65  2000-12-16       <NA>        NaN 2001-01-01 2000-12-23\n66        <NA>       <NA>        NaN 2000-09-17 2000-10-16\n67        <NA>       <NA>        NaN 2014-09-25       <NA>\n68  2009-03-07       <NA>        NaN 2009-03-16 2009-03-29\n69  2009-05-01 2010-02-11        NaN 2014-12-15       <NA>\n70        <NA>       <NA>        NaN 2014-10-06       <NA>\n71  1998-09-13       <NA>        NaN 1998-09-11 1998-09-20\n72  1998-05-27 1998-12-12        NaN 2001-08-05 2001-07-20\n73        <NA>       <NA>        NaN 2008-11-12 2008-12-19\n74        <NA>       <NA>        NaN 1996-09-09 1996-09-12\n75        <NA>       <NA>        NaN 2014-09-09       <NA>\n76        <NA>       <NA>        NaN 2014-12-30       <NA>\n77  1995-09-16 1995-12-16        NaN 1999-07-30 1999-08-07\n78        <NA>       <NA>        NaN 2014-12-30       <NA>\n79        <NA>       <NA>        NaN 1999-12-16 1999-12-25\n80        <NA>       <NA>        NaN 1999-03-13 1999-03-23\n81  1994-12-12       <NA>        NaN 1994-11-15 1994-12-19\n82  2009-06-12       <NA>        NaN 2009-05-16 2009-06-19\n83  2009-11-28 2010-02-12 2009-12-19 2010-01-26 2010-02-27\n84        <NA>       <NA>        NaN 2014-09-03       <NA>\n85  2009-05-10 2009-05-20 2008-06-27 2009-06-11 2009-06-08\n86  2005-05-11 2009-08-04        NaN 2014-06-24       <NA>\n87  2009-08-12       <NA>        NaN 2014-10-21       <NA>\n88  2004-04-18       <NA>        NaN 2004-03-25 2004-04-26\n89  2005-01-23       <NA>        NaN 2004-12-30 2005-01-30\n90        <NA>       <NA>        NaN 2014-06-23       <NA>\n91        <NA>       <NA>        NaN 1998-08-15 1998-08-29\n92  2007-10-11       <NA>        NaN 2007-10-05 2007-10-18\n93        <NA>       <NA>        NaN 2004-04-13 2004-05-15\n94  2001-06-19       <NA>        NaN 2001-07-02 2001-06-26\n95        <NA>       <NA>        NaN 2014-11-01       <NA>\n96  2000-11-10 2012-03-24        NaN 2012-03-23 2012-03-31\n97        <NA>       <NA>        NaN 2014-11-04       <NA>\n98        <NA>       <NA>        NaN 2014-08-19       <NA>\n99        <NA>       <NA>        NaN 1995-03-30 1995-05-02\n100       <NA>       <NA>        NaN 2014-11-01       <NA>\n101       <NA>       <NA> 2013-03-17 2014-10-29       <NA>\n102       <NA>       <NA>        NaN 2014-10-28       <NA>\n103       <NA>       <NA>        NaN 2001-06-14 2001-07-07\n104       <NA>       <NA>        NaN 2014-08-26       <NA>\n105       <NA>       <NA>        NaN 2009-11-21 2009-12-16\n106       <NA>       <NA>        NaN 2014-06-19       <NA>\n107       <NA>       <NA>        NaN 2014-12-30       <NA>\n108       <NA>       <NA>        NaN 1999-03-10 1999-03-21\n109 1999-06-09 2002-12-17 2002-04-26 2002-12-19 2003-01-06\n110       <NA>       <NA>        NaN 2014-11-11       <NA>\n111 1999-05-07 2000-10-30        NaN 2003-03-22 2003-03-25\n112       <NA>       <NA> 2003-02-25 2006-04-06 2006-04-25\n113       <NA>       <NA>        NaN 1998-03-26 1998-03-21\n114 2005-01-21 2005-02-07        NaN 2005-03-06 2005-03-17\n115 1998-03-02 2006-12-11        NaN 2006-11-23       <NA>\n116 2014-03-26       <NA>        NaN 2014-09-02       <NA>\n117       <NA>       <NA>        NaN 2014-10-06       <NA>\n118 2003-08-07 2004-05-31 1999-12-26 2005-05-19 2005-05-18\n119 2003-07-21       <NA>        NaN 2003-07-11 2003-07-28\n120 2000-05-26 2007-01-12        NaN 2009-05-08 2009-06-04\n121 2008-12-04 2009-06-16        NaN 2009-05-17 2009-06-23\n122 2010-03-25 2011-01-28        NaN 2014-12-30       <NA>\n123 1996-05-18       <NA>        NaN 1996-05-16 1996-05-25\n124 2002-08-31       <NA>        NaN 2002-08-19 2002-09-07\n125 2000-08-05 2005-07-19 2009-03-07 2009-10-08 2009-10-26\n126       <NA>       <NA>        NaN 1998-08-19 1998-09-21\n127       <NA>       <NA>        NaN 2014-06-25       <NA>\n128 1998-04-20       <NA>        NaN 1998-03-26 1998-04-27\n129 2001-12-24 2005-01-29        NaN 2014-09-01       <NA>\n130 2011-08-23 2012-01-12        NaN 2012-01-31 2012-02-19\n131       <NA>       <NA>        NaN 2002-06-28 2002-06-14\n132 2011-11-10       <NA>        NaN 2011-11-30 2011-12-25\n133       <NA>       <NA>        NaN 1999-03-29 1999-05-02\n134 1996-05-22 1997-09-20 2000-04-27 2000-05-03 2000-05-21\n135       <NA>       <NA>        NaN 2014-12-30       <NA>\n136       <NA>       <NA>        NaN 2014-12-30       <NA>\n137       <NA>       <NA>        NaN 2014-08-27       <NA>\n138       <NA>       <NA>        NaN 2004-02-15 2004-03-06\n139 2012-09-26       <NA>        NaN 2014-10-02       <NA>\n140 2004-06-30 2004-08-21        NaN 2004-09-13 2004-10-01\n141       <NA>       <NA>        NaN 2014-10-09       <NA>\n142       <NA>       <NA>        NaN 2014-06-16       <NA>\n143 2011-01-25       <NA>        NaN 2011-01-29 2011-02-01\n144       <NA>       <NA>        NaN 2009-12-20 2009-12-31\n145       <NA>       <NA>        NaN 2010-06-20 2010-07-07\n146 1998-08-30       <NA>        NaN 1998-09-13 1998-09-06\n147       <NA>       <NA>        NaN 2014-11-04       <NA>\n148 2004-06-23       <NA>        NaN 2004-06-09 2004-06-30\n149       <NA>       <NA>        NaN 2002-03-09 2002-04-13\n150 2008-06-05 2008-07-05        NaN 2010-05-18 2010-05-04\n151       <NA>       <NA>        NaN 2014-09-22       <NA>\n152 2013-11-05       <NA>        NaN 2014-10-28       <NA>\n153       <NA>       <NA>        NaN 2014-07-30       <NA>\n154       <NA>       <NA>        NaN 2014-10-14       <NA>\n155       <NA>       <NA>        NaN 2014-10-28       <NA>\n156       <NA>       <NA> 2011-06-21 2012-01-20 2012-01-10\n157       <NA>       <NA>        NaN 2014-10-09       <NA>\n158       <NA>       <NA>        NaN 2014-09-29       <NA>\n159 2013-02-16       <NA>        NaN 2014-08-11       <NA>\n160       <NA>       <NA>        NaN 2014-10-20       <NA>\n\n[[2]]\n     id        doV   a1c chol crea\n1     1 1993-05-07  87.3  3.9   83\n2     2 1993-05-05  66.5  6.6   83\n3     3 1993-05-11  73.0  5.6   68\n4     4 1993-05-12  61.2  5.2   97\n5     5 1993-02-25 102.7  6.0  149\n6     6 1993-03-18  93.4  4.8   55\n7     7 1993-03-16  94.5  8.6   56\n8     8 1993-03-12 103.9  5.1   78\n9     9 1993-03-16  46.4  4.2  123\n10   10 1993-01-21  84.4  5.4   79\n11   11 1993-01-28  47.9  8.9   74\n12   12 1993-02-19  86.4  5.3   84\n13   13 1993-03-23  80.9  6.0   65\n14   14 1993-02-03  88.3  5.7   52\n15   15 1993-01-19  83.8  6.3   61\n16   16 1993-01-20  47.9  6.8   61\n17   17 1993-05-19  78.0  5.7   52\n18   18 1993-05-20 106.2  4.1   62\n19   19 1993-05-11  53.1  9.5   98\n20   20 1993-05-13  65.4  5.7   46\n21   21 1993-05-23  73.0  4.9   82\n22   22 1993-05-21  72.1  5.3   74\n23   23 1993-01-25  88.8  6.6   79\n24   24 1993-03-12  69.4  6.9   52\n25   25 1993-03-04  65.6  7.4   88\n26   26 1993-03-20  66.5  5.4   44\n27   27 1993-03-24  76.2  4.0   71\n28   28 1993-02-25  38.3  5.3   61\n29   29 1993-04-16 113.7  4.7   54\n30   30 1993-05-27  66.7  5.9  149\n31   31 1993-03-28  88.1  7.8   99\n32   32 1993-03-17 111.0  7.1   90\n33   33 1993-03-10  35.8  3.3   91\n34   34 1993-02-04  56.5  5.2   86\n35   35 1993-06-28  56.3  6.8   88\n36   36 1993-03-19  65.6  4.8   48\n37   37 1993-01-29  51.5  5.8   71\n38   38 1993-02-13  63.9  5.4   94\n39   39 1993-02-04  56.2  5.9   67\n40   40 1993-03-28  86.6  8.5   41\n41   41 1993-01-22  51.0  5.1  137\n42   42 1993-04-04  48.1  5.6   96\n43   43 1993-02-11  70.6  6.2   73\n44   44 1993-02-08  94.8  5.7   71\n45   45 1993-02-23  52.8  4.9   55\n46   47 1993-05-20  60.5  5.9   61\n47   48 1993-06-02  44.6  4.0   47\n48   50 1993-05-31  55.6  5.0  110\n49   51 1993-06-01  79.3  6.5   63\n50   52 1993-02-24 109.6  6.9   53\n51   53 1993-03-04  40.4  7.1   62\n52   54 1993-02-26  51.4  5.6   44\n53   55 1993-04-28  85.8  5.6   60\n54   56 1993-03-15  98.9  5.3  106\n55   57 1993-01-24  76.6  7.0   28\n56   58 1993-02-12  60.0  5.3  144\n57   59 1993-06-04  74.8  5.5   62\n58   60 1993-06-11  73.2  5.6  120\n59   61 1993-06-10  43.1  4.1   72\n60   62 1993-06-03 104.1  7.9   49\n61   63 1993-04-02 107.9  6.2   85\n62   64 1993-02-18 108.3  4.7  109\n63   65 1993-04-19  92.4  4.7   71\n64   66 1993-02-26  55.4  5.5  125\n65   67 1993-04-14  67.8  6.0   84\n66   68 1993-04-14  38.2  8.4  108\n67   69 1993-03-01  48.6  3.2  112\n68   70 1993-02-16  74.3  7.7  123\n69   71 1993-04-18  97.5  6.7  121\n70   72 1993-04-15  97.3  5.9  121\n71   73 1993-02-09  89.6  5.7   65\n72   74 1993-04-21  63.6  6.3   41\n73   75 1993-02-28  71.6  6.7   85\n74   76 1993-03-01 100.9  5.9   62\n75   77 1993-04-23  52.9  6.8   99\n76   78 1993-05-02  47.7  5.5   82\n77   79 1993-05-01  82.9  6.5  108\n78   80 1993-03-19  57.3  6.6   55\n79   81 1993-03-24  99.8  6.2   79\n80   82 1993-01-25  54.1  5.3  127\n81   83 1993-01-13  53.8  4.9   77\n82   84 1993-03-03  63.7  5.7   60\n83   85 1993-04-26  56.5  5.7   45\n84   86 1993-05-03  67.7  5.0   86\n85   87 1993-04-19  54.2  4.6   90\n86   88 1993-03-15  78.7  8.3  101\n87   89 1993-06-20  61.2  4.0   82\n88   90 1993-08-02  59.4  3.6   79\n89   91 1993-07-25  69.5  4.5   48\n90   92 1993-08-29  53.2  5.7   94\n91   93 1993-08-05  73.3  5.4  124\n92   94 1993-08-02  70.1  3.6  107\n93   95 1993-08-27  56.7  5.2  109\n94   96 1993-07-31  60.6  6.0   92\n95   97 1993-08-01  45.5  4.6   80\n96   98 1993-07-31  80.7  4.3   72\n97  100 1993-08-10  88.2  7.7   90\n98  101 1994-01-19  72.8  4.0   61\n99  102 1993-08-11  60.4  4.2   60\n100 103 1993-08-21  83.3  5.8  107\n101 104 1993-08-22  69.5  4.7   80\n102 105 1994-02-04  59.6  4.9   57\n103 107 1993-08-27  63.7  7.0   54\n104 108 1993-08-24  38.6  4.5  103\n105 110 1993-08-24  42.4  4.8   52\n106 111 1993-09-03  41.0  6.3   80\n107 112 1993-10-09  74.3  6.8   69\n108 113 1993-10-09  50.9  5.3   89\n109 114 1993-10-08  83.6  5.8  127\n110 115 1993-10-01  47.7  6.0   63\n111 116 1993-10-08  88.1  5.2   62\n112 118 1993-10-19  63.5  6.3   73\n113 119 1993-10-10  52.9  7.4   78\n114 120 1993-10-09  77.5  3.1   76\n115 121 1993-10-18  48.9  4.6   83\n116 123 1993-11-06  67.5  5.1   58\n117 126 1993-10-27  70.4  5.7   87\n118 128 1993-11-08  48.7  5.0  100\n119 129 1993-11-01  91.5  4.4   93\n120 130 1993-11-02  89.2  6.2   86\n121 131 1993-11-02  48.4  4.1   98\n122 133 1994-03-22  72.3  6.8   51\n123 134 1993-11-09  82.6  5.5   87\n124 135 1993-11-15  75.0  6.3   56\n125 136 1993-11-20 100.1  5.7   94\n126 137 1993-11-25  53.7  5.2   75\n127 138 1993-11-28  52.0  4.7   47\n128 139 1993-11-30  69.6  7.8   76\n129 140 1993-12-10  76.9  5.7   58\n130 142 1993-11-27  81.7  4.6   73\n131 143 1993-12-10  69.3  4.6   93\n132 144 1993-12-05  74.2  6.6   91\n133 145 1994-01-14  65.1  4.5   57\n134 146 1994-01-25  72.1  4.3   58\n135 147 1994-01-25  48.6  4.6  126\n136 148 1993-12-31  82.2  8.4   67\n137 150 1994-01-13  57.6  6.4   47\n138 151 1994-01-22  50.1  3.6   61\n139 152 1994-01-25  89.5  6.8   95\n140 153 1994-01-23  69.8  4.3   48\n141 155 1994-01-21  46.5  3.5  126\n142 156 1994-01-19  56.4  4.1   59\n143 157 1994-03-15  81.2  6.4   66\n144 158 1994-02-02  47.7  4.6   87\n145 159 1994-01-22  64.0  4.4   62\n146 160 1994-01-26  90.9  5.9  126\n147 161 1994-01-24  65.6  4.9   83\n148 163 1994-02-07  61.0  6.2  141\n149 165 1994-02-21  66.5  6.7   66\n150 166 1994-02-20  62.2  6.1   80\n151 167 1994-02-17  73.6  6.0   96\n152 168 1994-02-25  86.2  6.5  101\n153 169 1994-05-02  51.7  5.3   62\n154 170 1994-05-04  77.1  5.0   54\n155 171 1994-04-30  61.2  5.7  108\n156 172 1994-05-11  49.7  5.0   48\n157 173 1994-05-14  70.5  4.1   59\n158 174 1994-05-23 103.0  4.6  110\n159 175 1994-05-30  51.3  4.3  106\n160 176 1994-05-20  86.7  5.7   62\n161   1 1995-06-25  68.9  4.2   73\n162   2 1995-06-28  54.8  5.7  105\n163   3 1995-07-01  79.6  4.1   78\n164   4 1995-06-27 102.3  4.8  106\n165   5 1995-07-07  54.7  8.8  140\n166   6 1995-07-02 100.1  8.8  184\n167   7 1995-07-04 103.4  6.0   60\n168   8 1995-07-06  52.8  4.0  197\n169   9 1995-06-24  73.7  3.3  216\n170  10 1995-07-07  60.5  5.5  176\n171  11 1995-06-28  63.2  4.9   91\n172  12 1995-06-29 109.8  4.6   63\n173  13 1995-07-05  55.1  4.9   67\n174  14 1995-07-07  79.5  4.2   51\n175  15 1995-07-04  59.5  4.8  123\n176  16 1995-07-06  87.3  4.5  155\n177  17 1995-07-06  66.1  3.6   49\n178  18 1995-06-24  90.2  4.7   59\n179  19 1995-07-02  74.4  8.7   72\n180  20 1995-07-04  84.2  6.0  174\n181  21 1995-06-25  94.7  4.9   75\n182  22 1995-07-05  57.7  4.9   60\n183  23 1995-06-24 110.4  5.9  167\n184  24 1995-07-03  58.5  4.8   85\n185  25 1995-06-25  80.4  7.4   75\n186  26 1995-07-02  89.5  5.8  100\n187  27 1995-07-05  58.0  3.8   61\n188  28 1995-06-24  37.9  7.0   75\n189  29 1995-06-27  97.4  3.2   82\n190  30 1995-07-04  62.2  5.7   81\n191  31 1995-06-26  91.8  6.1  149\n192  32 1995-07-01 104.1  5.6   87\n193  33 1995-06-26  45.9  4.0   83\n194  34 1995-07-04  48.9  4.3   65\n195  35 1995-07-02 109.4  7.5  109\n196  36 1995-07-01  69.2  4.7   70\n197  37 1995-06-26  47.6  3.8   61\n198  38 1995-07-03  82.0  6.7  178\n199  39 1995-07-06  71.1  4.5  123\n200  40 1995-06-26  68.0  6.6   94\n201  41 1995-07-03  43.5  4.5   97\n202  42 1995-07-03  78.1  5.5  113\n203  43 1995-06-28  80.0  7.1  138\n204  44 1995-06-30 104.5  6.3   99\n205  45 1995-06-29  61.1  4.5   63\n206  47 1995-06-29  89.9  5.4   55\n207  48 1995-06-29  57.9  3.2   79\n208  50 1995-06-26  92.8  4.7   94\n209  51 1995-06-27  66.7  5.5   81\n210  52 1995-06-25  88.3  4.7  102\n211  53 1995-06-26  59.0  6.9   48\n212  54 1995-07-05  40.9  4.8   44\n213  55 1995-06-25  57.0  4.7   61\n214  56 1995-07-04  54.5  5.5  142\n215  57 1995-07-02  69.0  5.6   35\n216  58 1995-06-29  77.0  4.8  144\n217  59 1995-06-26  97.0  4.5   43\n218  60 1995-07-03  78.9  4.9   76\n219  61 1995-06-30  48.8  3.8  105\n220  62 1995-06-28  84.5  7.2   72\n221  63 1995-06-29  82.8  5.4   56\n222  64 1995-07-06  96.5  4.1  131\n223  65 1995-07-02  81.2  4.7   54\n224  66 1995-06-27  63.8  5.6  146\n225  67 1995-06-25  61.5  5.1   78\n226  68 1995-07-01  91.3  5.7   62\n227  69 1995-06-28  75.8  4.0   93\n228  70 1995-07-02  73.2  4.7  148\n229  71 1995-06-26  71.3  6.1   75\n230  72 1995-06-27  85.2  4.9  102\n231  73 1995-06-27  71.2  4.8  101\n232  74 1995-06-27  65.1  3.5   54\n233  75 1995-07-04  81.4  5.3  109\n234  76 1995-06-27  46.5  4.9  100\n235  77 1995-07-05  50.9  5.3   85\n236  78 1995-06-30  68.4  4.6  167\n237  79 1995-06-24  68.2  5.5  138\n238  80 1995-06-28  73.1  5.5   63\n239  81 1995-06-29  78.5  6.1   86\n240  82 1995-06-25  70.2  5.5   86\n241  84 1995-07-03  81.5  5.1   68\n242  85 1995-06-26  84.8  4.6   88\n243  86 1995-07-01  61.4  7.1   65\n244  87 1995-06-25  85.9  4.1  117\n245  88 1995-07-05  74.8  3.9   99\n246  89 1995-06-26  50.3  3.4  220\n247  90 1995-07-03  90.1  4.5   52\n248  91 1995-07-03  74.1  4.6   87\n249  92 1995-06-25  57.5  4.9   81\n250  93 1995-07-01  59.3  4.6   53\n251  94 1995-07-04  78.7  3.9   72\n252  95 1995-07-07  43.8  4.7  122\n253  96 1995-07-07  65.5  4.4  103\n254  97 1995-07-07  43.2  4.5  110\n255  98 1995-07-01  67.5  4.2  116\n256 100 1995-06-29  77.7  6.1  111\n257 101 1995-06-24  62.3  4.3   61\n258 103 1995-07-02  80.4  5.1   54\n259 104 1995-06-24  66.3  5.6   68\n260 105 1995-07-04  81.1  4.8  126\n261 107 1995-07-01  60.2  5.8   53\n262 108 1995-06-28  65.9  5.8   88\n263 110 1995-06-25  36.3  4.7  111\n264 111 1995-06-25  60.2  5.3  131\n265 112 1995-06-26  95.0  5.7   57\n266 113 1995-06-24  63.0  4.9   64\n267 114 1995-07-06  97.8  5.9  121\n268 115 1995-07-01  46.7  4.5   68\n269 116 1995-06-24 109.3  5.2   88\n270 118 1995-07-02  73.5  6.1   92\n271 119 1995-07-07  52.6  4.0   67\n272 120 1995-07-02  78.9  3.6   54\n273 121 1995-07-03  61.0  5.1  118\n274 123 1995-07-03  63.1  5.0  105\n275 126 1995-06-29  74.1  5.8  114\n276 129 1995-07-01  66.2  4.4   94\n277 130 1995-06-29  87.0  5.9  136\n278 131 1995-07-06  44.2  4.5   69\n279 133 1995-07-03  44.4  6.1   83\n280 134 1995-06-26  84.7  5.7   71\n281 135 1995-07-07  64.7  4.3   55\n282 136 1995-06-28 119.7  5.9  106\n283 137 1995-06-25  52.6  4.5  106\n284 138 1995-07-04  56.8  3.9   75\n285 139 1995-07-01  61.9  5.8  125\n286 140 1995-07-07  89.6  5.7   47\n287 142 1995-07-01 121.1  4.5   62\n288 143 1995-07-02  55.2  4.4  124\n289 144 1995-06-30  92.6  7.0  138\n290 145 1995-07-04  96.1  5.3  121\n291 146 1995-07-03  72.3  4.4  115\n292 147 1995-06-27  52.3  4.4  142\n293 148 1995-07-07 101.7  6.5   45\n294 151 1995-07-05  63.3  3.3  114\n295 152 1995-06-30  73.1  6.2  101\n296 153 1995-06-27  52.7  3.7  100\n297 155 1995-06-28  46.3  3.8   96\n298 156 1995-07-06  49.2  4.2  116\n299 157 1995-07-05  80.6  5.5   66\n300 158 1995-06-25  47.6  4.9  145\n301 159 1995-07-05  50.5  5.0   67\n302 160 1995-06-28  99.3  6.7   96\n303 161 1995-06-30  57.2  4.5  110\n304 163 1995-06-27  55.7  6.2   94\n305 165 1995-07-05  58.3  6.1   63\n306 166 1995-06-29  62.3  5.2  102\n307 167 1995-07-01  67.5  5.1   50\n308 168 1995-06-27  76.1  5.3   73\n309 169 1995-07-05  44.4  5.5   85\n310 170 1995-06-25  57.0  5.6   90\n311 171 1995-06-24  49.5  5.0  103\n312 172 1995-07-07  76.4 14.0  126\n313 173 1995-07-03  57.7  3.9   59\n314 174 1995-07-05  58.1  5.0   67\n315 175 1995-06-25  60.0  3.9   86\n316 176 1995-06-25  77.9  4.9   52\n317   1 1997-06-24  63.7  4.4   63\n318   2 1997-07-05  49.5  6.8   50\n319   3 1997-07-07  73.0  4.7   83\n320   4 1997-07-06  73.6  5.7  118\n321   5 1997-07-01  41.9  5.8  141\n322   6 1997-07-01 108.6  8.7   67\n323   7 1997-06-30  88.4  5.8   53\n324   8 1997-06-26  52.9  3.5  287\n325  10 1997-06-24  75.8  5.8   73\n326  12 1997-06-27 129.8  4.7   79\n327  13 1997-06-25  65.2  4.7   83\n328  14 1997-07-05  59.1  3.5   77\n329  15 1997-07-03  49.9  3.5   74\n330  16 1997-06-30  61.8  6.5   96\n331  17 1997-07-02  61.9  3.8   60\n332  18 1997-07-03  72.8  6.9  100\n333  19 1997-06-27  36.1  7.0   82\n334  20 1997-07-04  93.4  6.3   95\n335  21 1997-07-03  52.8  5.0   74\n336  22 1997-06-25  49.5  4.5   48\n337  23 1997-06-29  42.3  4.7  158\n338  24 1997-06-24  69.1  5.0  107\n339  25 1997-07-07  81.4  6.8   85\n340  26 1997-06-29  86.5  6.0   64\n341  27 1997-06-28  58.0  4.4   75\n342  28 1997-06-30  60.3  4.8   85\n343  29 1997-07-03 110.4  4.5  112\n344  30 1997-06-24  63.9  4.4  150\n345  31 1997-06-30  83.5  6.4   69\n346  32 1997-07-02  83.7  5.1   57\n347  33 1997-07-07  50.5  3.8   92\n348  34 1997-07-04  51.4  5.0  108\n349  35 1997-07-06  76.6  7.3  148\n350  36 1997-06-30  74.0  5.4   77\n351  37 1997-06-27  61.0  4.6   70\n352  38 1997-07-02  83.5  7.9  129\n353  39 1997-07-05  62.1  5.1  112\n354  40 1997-06-26  79.4  6.0   68\n355  41 1997-06-28  37.5  4.3  151\n356  42 1997-06-27  83.9  5.6  157\n357  43 1997-07-06  96.5  7.1  166\n358  44 1997-07-04  76.9  6.6  119\n359  45 1997-07-06  88.8  4.8   56\n360  47 1997-07-06 105.5  7.8   79\n361  48 1997-06-29  71.8  2.8   71\n362  50 1997-07-02  74.6  5.2  124\n363  51 1997-07-02  55.0  4.5   86\n364  52 1997-06-27  70.1  4.6  100\n365  53 1997-06-25  66.4  6.1   74\n366  54 1997-06-28  44.1  5.6   51\n367  55 1997-07-01  49.2  5.2   51\n368  56 1997-06-30  42.2  4.1   86\n369  57 1997-07-05 101.1  6.7   54\n370  58 1997-06-27  72.1  5.0   97\n371  59 1997-07-03  92.5  4.8   80\n372  60 1997-06-25  69.0  5.4  107\n373  61 1997-06-28  63.7  3.9   88\n374  62 1997-06-26 106.2  9.1   72\n375  63 1997-06-24  68.6  5.7   61\n376  64 1997-07-01  90.4  4.1   77\n377  65 1997-06-25  78.2  4.1   85\n378  67 1997-07-02  52.5  5.2  112\n379  68 1997-07-05  56.9  4.8   71\n380  69 1997-07-03  53.8  4.1  120\n381  70 1997-06-27  80.1  5.8  123\n382  71 1997-07-05  78.6  6.6  110\n383  72 1997-07-07  79.1  6.0   58\n384  73 1997-07-01  47.3  5.6   63\n385  74 1997-07-02  50.2  5.0  102\n386  75 1997-06-29  51.1  4.9   75\n387  77 1997-06-24  56.2  5.2  112\n388  78 1997-06-29  58.9  4.2  147\n389  79 1997-06-25  73.0  4.9  137\n390  80 1997-07-03  72.2  5.0   93\n391  81 1997-06-24  70.0  5.1   82\n392  82 1997-06-27  72.2  5.7  132\n393  85 1997-07-06  87.1  3.4   91\n394  86 1997-07-05  54.9  4.9   61\n395  87 1997-07-02  74.5  4.1   65\n396  88 1997-06-30  79.8  5.2  104\n397  89 1997-07-03  48.5  4.0  191\n398  90 1997-06-25  59.6  4.4   67\n399  91 1997-07-02  61.4  3.7   79\n400  92 1997-07-01  57.9  5.0   94\n401  93 1997-06-25  82.6  5.3   50\n402  94 1997-07-07  61.6  4.0   77\n403  95 1997-07-03  68.0  4.6  147\n404  96 1997-07-06  60.5  5.6   65\n405  97 1997-07-03  56.0  4.8   49\n406  98 1997-07-05  49.5  4.4  155\n407 100 1997-06-25  81.9  7.8   77\n408 101 1997-06-26  50.6  4.6   75\n409 103 1997-07-06  59.7  4.5  106\n410 104 1997-06-30  60.5  3.8   64\n411 105 1997-06-30  51.4  4.6   92\n412 107 1997-06-26  52.0  5.6  111\n413 108 1997-06-29  46.9  4.0   81\n414 110 1997-06-30  57.1  4.7   75\n415 111 1997-07-02  48.6  5.7   74\n416 112 1997-07-06  73.7  5.6   35\n417 113 1997-06-28  78.5  5.7  101\n418 114 1997-06-25  70.4  5.5  114\n419 115 1997-07-02  47.8  5.2  100\n420 116 1997-07-03 123.1  5.7   60\n421 118 1997-07-01  48.9  6.3   69\n422 119 1997-07-07  34.7  3.4   65\n423 120 1997-06-30  65.0  3.4   90\n424 121 1997-07-04  61.8  5.6  128\n425 123 1997-07-02  79.0  5.1   89\n426 126 1997-06-25  68.7  4.6   81\n427 129 1997-06-29  70.5  4.3  116\n428 130 1997-06-24  70.8  5.6  119\n429 131 1997-07-07  47.3  5.2   90\n430 133 1997-07-02  62.9  5.9   96\n431 135 1997-06-27  98.8  5.2   56\n432 136 1997-07-03 113.7  5.9   69\n433 137 1997-06-24  34.3  4.9  120\n434 138 1997-07-04  44.2  3.9   96\n435 139 1997-06-25  65.6  5.7  133\n436 140 1997-06-26  81.2  6.2   93\n437 142 1997-06-30  68.9  4.3  103\n438 143 1997-07-05  73.6  5.4  236\n439 144 1997-06-27  77.0  6.2  138\n440 145 1997-07-04  60.9  4.5   60\n441 146 1997-06-26  72.3  5.2   66\n442 148 1997-07-04 119.0  7.0   51\n443 151 1997-07-01  85.4  4.4  104\n444 152 1997-06-26  62.5  5.0   55\n445 153 1997-06-30  45.6  3.8  106\n446 155 1997-07-06  50.8  3.8   84\n447 156 1997-06-29  59.4  4.3   75\n448 157 1997-07-03  70.1  5.5   84\n449 158 1997-06-27  54.4  4.4  109\n450 159 1997-06-26  43.9  3.9  111\n451 160 1997-06-24  93.7  5.9   99\n452 161 1997-06-25  52.9  4.5   91\n453 163 1997-06-29  42.8  5.1  117\n454 165 1997-07-03  57.7  5.6   78\n455 166 1997-06-27  85.6  5.6   87\n456 167 1997-06-29  81.8  5.1   68\n457 168 1997-07-04  78.9  6.7   92\n458 169 1997-06-30  52.3  4.7  126\n459 170 1997-07-05  59.8  4.6   61\n460 171 1997-07-02  82.0  5.5   59\n461 172 1997-06-28  92.3  5.6   85\n462 173 1997-07-07  69.8  4.7   68\n463 174 1997-06-26  52.6  4.8  118\n464 175 1997-07-07  78.3  4.8   75\n465 176 1997-06-24  91.3  6.3   86\n466   1 2001-01-31  50.6  3.0  105\n467   2 2001-10-29  69.4  4.2   63\n468   3 2001-02-01  70.5  5.8  158\n469   4 2001-01-28  74.4  4.2  141\n470   6 2001-01-10  91.5  7.4   59\n471   7 2001-01-17  57.6  5.7   70\n472   8 2001-08-27  75.2  3.3  130\n473  10 2001-01-14  63.4  4.7  124\n474  11 2001-11-08  89.0  9.1  138\n475  12 2001-04-07  76.3  5.7  196\n476  13 2001-02-05  69.8  3.8   59\n477  14 2001-01-09  58.3  4.3  150\n478  15 2001-08-11  80.2  4.1  189\n479  16 2001-01-09  93.1  5.6  167\n480  17 2001-01-17  68.7  3.6   45\n481  18 2001-02-03  80.0  4.6  107\n482  19 2001-03-30  59.3  7.7  110\n483  20 2001-02-08  90.4  6.7   65\n484  21 2001-10-22  66.5  5.9  124\n485  22 2001-03-26  53.2  2.7   99\n486  24 2001-10-27  62.8  4.0   84\n487  25 2001-01-24 114.1  7.9  128\n488  26 2001-04-18  75.5  5.4  113\n489  27 2001-04-05  41.8  6.8  132\n490  28 2001-11-04  62.7  5.1  122\n491  29 2001-09-04  76.6  5.0   83\n492  30 2001-08-12  54.6  4.3  106\n493  31 2001-03-29  73.5  5.2  112\n494  33 2001-08-20  42.9  3.4  105\n495  34 2001-01-16  37.7  3.6  154\n496  35 2001-04-02 110.7  7.6  114\n497  36 2001-08-27  64.0  6.3   61\n498  37 2001-01-09  62.0  4.1   91\n499  38 2001-01-08  85.1  3.9  161\n500  39 2001-03-16  62.2  4.4  144\n501  41 2001-04-25  44.7  3.8  156\n502  42 2001-03-17  91.7  4.3  109\n503  43 2001-03-25  76.8  5.6  243\n504  45 2001-03-28  57.8  5.3   96\n505  47 2001-01-11 147.6  7.9   95\n506  50 2001-03-29  80.4  5.2   97\n507  51 2001-04-07  62.5  4.3   73\n508  52 2001-04-18  84.9  5.0  121\n509  53 2001-01-18  69.0  5.6   98\n510  54 2001-04-06  51.5  3.9   70\n511  55 2001-03-31  52.1  4.6   58\n512  56 2001-01-13  36.6  3.1  167\n513  58 2001-01-19  79.2  5.7   76\n514  59 2001-10-26  88.6  3.6  114\n515  61 2001-04-07  51.3  3.9   88\n516  62 2001-04-20  93.7  6.3   82\n517  64 2001-03-31  80.9  4.4   85\n518  65 2001-02-11  76.0  3.1   91\n519  69 2001-01-18  75.9  3.5  117\n520  70 2001-01-07  68.9  6.5   77\n521  71 2001-01-27  86.1  7.4  157\n522  72 2001-02-05  69.0  5.3  110\n523  74 2001-05-08  45.5  3.6  119\n524  75 2001-09-02  75.8  5.3  157\n525  77 2001-01-12  35.7  3.6  129\n526  78 2001-03-20  65.0  5.5  141\n527  80 2001-01-25  67.8  6.8   97\n528  85 2001-02-11  97.6  5.3   84\n529  86 2001-01-28  65.3  4.5   70\n530  87 2001-10-31  63.0  3.1   78\n531  88 2001-03-21  76.9  4.3  168\n532  89 2001-08-19  53.0  4.0  143\n533  90 2001-10-07  99.7  3.8   75\n534  91 2001-03-14  65.1  3.4  177\n535  92 2001-02-06  56.3  3.6   69\n536  94 2001-08-24  54.9  4.6   87\n537  95 2001-08-29  50.5  3.0  110\n538  96 2001-04-07  62.8  3.7  157\n539  97 2001-04-01  57.9  3.2   70\n540  98 2001-04-15  49.1  3.3   72\n541 100 2001-09-09  68.7  4.5  105\n542 101 2001-09-13  58.4  3.9  106\n543 103 2001-02-02  58.1  3.2  132\n544 104 2001-02-08  88.3  4.0   77\n545 105 2001-09-15  50.6  3.3   65\n546 107 2001-04-05  54.1  4.8   60\n547 108 2001-04-02  52.7  4.0   67\n548 110 2001-01-11  52.3  5.7   78\n549 111 2001-09-10  70.4  5.1  114\n550 112 2001-08-23  73.7  6.1   65\n551 114 2001-10-25  61.1  3.1  179\n552 115 2001-03-14  48.8  5.4   90\n553 116 2001-10-18  44.2  5.7  162\n554 118 2001-11-12  42.7  6.3  101\n555 120 2001-09-12  54.4  3.7   74\n556 121 2001-08-24  56.4  4.0  153\n557 123 2001-08-30  51.6  4.4  132\n558 126 2001-03-22  62.0  4.2  125\n559 128 2001-07-12    NA  4.5 1067\n560 129 2001-10-22  65.7  4.6  116\n561 130 2001-08-15  74.8  5.3   85\n562 131 2001-08-24  70.6  5.4   88\n563 133 2001-10-09  85.5  5.6  100\n564 135 2001-08-30  72.3  3.9   85\n565 136 2001-08-14  93.7  4.0  146\n566 138 2001-04-20  54.8  4.3   62\n567 140 2001-12-09  50.2  7.9   84\n568 142 2001-09-03  75.6  3.7   88\n569 143 2001-04-14  75.5  3.5  305\n570 144 2001-04-22  72.6  5.9  127\n571 147 2001-10-31  67.0  4.0  112\n572 148 2001-08-19  79.5  5.1   74\n573 151 2001-09-10  64.7  4.3   64\n574 152 2001-04-04  70.7  4.1   59\n575 153 2001-08-13  57.1  2.7   70\n576 155 2001-09-23  47.6  4.8  133\n577 156 2001-08-23  57.8  4.3   79\n578 158 2001-09-17  55.8  4.6  107\n579 159 2001-08-08  49.8  3.8  100\n580 161 2001-10-28  68.0  4.7   84\n581 163 2001-08-12  50.9  3.7   75\n582 165 2001-11-04 114.1  9.7   84\n583 166 2001-09-04  75.0  6.2   95\n584 167 2001-04-06  66.8  4.2  105\n585 168 2001-05-08  74.8  5.4  144\n586 169 2001-09-09  56.9  5.1  104\n587 170 2001-08-25  73.4  3.9   69\n588 171 2001-10-20  73.6  5.0  151\n589 172 2001-04-09  69.5  6.6   57\n590 173 2001-08-22  68.5  4.2   82\n591 174 2001-09-12  83.4  4.1   63\n592 175 2001-09-10  59.8  4.5   99\n593 176 2001-10-21  79.9  5.6   70\n594   1 2006-09-19  74.9  3.2  107\n595   2 2006-11-17  57.9  3.5   87\n596   6 2006-10-03 104.8  5.1  139\n597   8 2006-11-22  73.6  3.7  446\n598  10 2006-08-31  75.9  3.7  307\n599  13 2006-10-17  76.2  3.6   38\n600  14 2007-01-06  68.7  3.2   87\n601  15 2006-12-07  74.9  4.2  198\n602  16 2006-09-12  65.6  3.1  200\n603  17 2006-10-05  72.7  3.5  129\n604  18 2006-09-21  94.5  4.3   95\n605  19 2006-12-03  61.6  4.7   45\n606  20 2006-09-12  83.3  3.4  132\n607  21 2007-01-24  64.4  4.1  155\n608  22 2006-10-08  58.4  3.2   89\n609  24 2006-11-17  63.6  3.5   74\n610  25 2006-09-03  89.7  4.4   97\n611  27 2006-12-12  58.7  3.3  104\n612  28 2006-11-20  46.7  6.3   89\n613  31 2006-10-09  79.6  5.3   81\n614  33 2006-10-06  36.2  4.4   56\n615  34 2006-09-10  63.4  3.5  136\n616  36 2006-11-13  68.3  3.5   97\n617  37 2006-10-23  60.7  3.2   65\n618  39 2006-09-25  65.2  4.2   56\n619  44 2007-01-19  93.0  4.0  115\n620  45 2006-09-30  63.1  3.1   79\n621  48 2006-11-24  50.6  3.3  106\n622  51 2006-10-09  67.0  4.8  103\n623  52 2006-11-22  94.9  2.9   54\n624  54 2006-12-12  50.4  4.1   52\n625  55 2006-10-09  66.2  4.2   34\n626  56 2006-09-24  59.2  3.1  170\n627  61 2006-11-02  51.0  4.2  151\n628  62 2006-11-05  88.1  4.4  116\n629  65 2006-10-06  80.2  3.0   45\n630  69 2006-10-24  63.9  2.5   65\n631  70 2006-11-20  68.3  4.1  160\n632  71 2006-10-07  87.0  4.7  141\n633  75 2006-11-10  62.4  3.9  115\n634  77 2006-09-29  42.8  3.0  109\n635  78 2006-12-10  58.8  3.1  154\n636  80 2006-09-30  67.1  4.0  111\n637  84 2006-12-09  67.7  4.2  193\n638  85 2006-09-22  85.5  3.4  344\n639  86 2006-11-02  66.0  3.6   48\n640  87 2006-12-18  51.8  2.8  261\n641  88 2006-09-04  80.3  3.6  142\n642  89 2006-10-18  54.3  4.4  184\n643  92 2006-08-29  60.6  5.4   53\n644  94 2006-12-05  74.4  2.9   52\n645  97 2006-12-18  42.5  3.4  109\n646  98 2006-12-09  67.2  2.5   94\n647 100 2006-12-13  79.0  5.2  102\n648 101 2006-11-13  59.8  3.8  130\n649 103 2006-10-24  60.5  3.5  160\n650 104 2006-09-11  71.3  5.2  211\n651 105 2006-12-10  55.9  2.9   66\n652 108 2006-10-14  44.8  3.7   72\n653 110 2007-01-14  46.5  4.4   71\n654 111 2006-10-06  51.1  3.8   45\n655 112 2006-12-23  83.4  3.5   63\n656 115 2006-09-26  54.6  3.8   62\n657 121 2006-11-24  55.3  4.8   95\n658 123 2006-12-01  70.0  4.1   73\n659 126 2006-10-04  61.1  3.6   98\n660 130 2006-10-19  86.8  2.6  119\n661 131 2006-11-23  55.6  2.7  104\n662 133 2007-01-15  65.1  5.4   53\n663 136 2007-01-16 117.4  3.2  195\n664 138 2006-10-03  46.1  3.9   39\n665 140 2007-01-09  82.2  5.6   48\n666 142 2006-11-05  83.1  2.8  115\n667 144 2006-11-27  81.8  3.9  119\n668 148 2006-09-13 104.7  4.3   80\n669 152 2006-11-06  70.3  4.1   83\n670 155 2006-10-24  41.4  4.7   78\n671 156 2006-11-03  56.9  2.9   78\n672 157 2006-12-23  86.9  5.5  231\n673 158 2007-01-18  50.0  3.7  189\n674 159 2006-09-11  59.7  3.1   83\n675 161 2006-11-11  63.2  3.8   65\n676 166 2006-09-05  66.4  5.6  146\n677 167 2006-11-01  70.8  3.6   70\n678 168 2006-12-17  82.5  3.5  159\n679 169 2006-11-07  48.3  4.3   77\n680 170 2006-09-29  74.3  3.0   56\n681 171 2006-11-17  67.7  3.0   91\n682 172 2006-10-07  74.6  3.3  133\n683 173 2006-10-12  73.0  5.7   44\n684 174 2006-10-24  77.5  3.4  117\n685 175 2006-11-20  57.6  5.3  150\n686 176 2006-11-06  86.6  3.5   96\n687   1 2014-10-06  32.8  4.2  171\n688   2 2014-07-31  58.1  3.7   63\n689   6 2014-09-01  43.6  6.0  555\n690  13 2014-09-20  50.1  2.7   73\n691  15 2014-12-04  75.5  3.7  213\n692  18 2014-12-25  78.6  3.7  135\n693  19 2014-12-25  45.7  6.1   99\n694  20 2014-08-30  58.5  3.7   88\n695  21 2014-10-19  53.4  3.3  120\n696  22 2014-10-14  38.3  3.2   81\n697  25 2014-08-07  63.8  4.8  255\n698  28 2014-07-30  51.7  4.7  110\n699  33 2014-10-30  58.8  3.2   73\n700  34 2014-09-23  49.8  3.5  251\n701  36 2014-12-02  48.3  3.6   77\n702  39 2014-09-02  85.8  4.4  145\n703  44 2014-08-18    NA   NA  118\n704  45 2014-09-28  64.3  3.6   60\n705  51 2014-10-12  53.1  3.0  114\n706  52 2014-09-02  57.2  3.6   82\n707  54 2014-09-22  61.8  3.5   36\n708  55 2014-08-12  44.7  4.2   74\n709  61 2014-10-28  68.1  4.7  122\n710  65 2014-12-31    NA  5.1   NA\n711  69 2014-09-18  59.0  2.2  101\n712  71 2014-12-09  47.7  2.8  109\n713  72 2014-10-04  63.1  4.1   58\n714  77 2014-09-05  37.7  3.6  176\n715  78 2014-12-25  53.4  2.5  158\n716  80 2015-01-03  81.7  2.4   95\n717  86 2014-09-09  49.6  5.2  117\n718  88 2014-06-28  39.1  3.1  157\n719  89 2014-10-25  64.8  2.7  141\n720  92 2014-06-18  61.2  5.7   72\n721  97 2014-10-26  57.1  3.7   66\n722 100 2014-11-02  38.3  5.5   69\n723 101 2014-08-24  86.4  3.5  153\n724 103 2014-11-01  49.0  3.5  139\n725 104 2014-10-27  51.8  4.4  492\n726 105 2014-11-01  41.8  3.4   86\n727 108 2014-08-19  42.6  3.4   78\n728 111 2014-06-21  53.8  5.1   56\n729 112 2014-12-25  72.4  4.5   91\n730 115 2014-11-16  42.7  3.5   74\n731 123 2014-09-06  48.3  3.1   52\n732 126 2014-10-10  56.7   NA   NA\n733 138 2014-06-29  78.3  4.7  135\n734 140 2014-09-03  68.1  5.4  110\n735 147 2014-12-29  56.5  3.2  146\n736 148 2014-12-24  41.2  5.8   46\n737 150 2014-08-23    NA   NA   58\n738 152 2014-09-26 108.5  6.3   43\n739 155 2014-10-03  48.9  4.5  154\n740 156 2014-06-10  38.9  3.4  106\n741 161 2014-11-02  39.8  4.9   84\n742 167 2014-09-18  37.6  4.8   48\n743 168 2014-11-02  55.5  3.7  211\n744 169 2014-08-04  60.3  3.9   47\n745 170 2014-10-16  76.3  4.3   54\n746 171 2014-10-31  53.3  3.4  136\n747 173 2014-10-13  84.4  4.3  134\n748 174 2014-09-25  62.0  3.1   74\n749 175 2014-08-07  78.5  2.2  149\n750 176 2014-10-16  86.3  3.9  126\n\n[[3]]\n     id       doTr state\n1     1 1993-06-12   Mic\n2     1 1995-05-13  Norm\n3     1 2000-01-26   Mic\n4     1 2001-12-26  Norm\n5     1 2007-04-27   Mic\n6     2 1993-10-15  Norm\n7     2 1997-09-15   Mic\n8     2 1997-10-14   Mac\n9     2 2003-06-05   Mic\n10    2 2009-05-29   Mic\n11    3 1993-07-22   Mic\n12    3 1995-07-06   Mic\n13    3 1997-03-18   Mac\n14    4 1994-09-05   Mic\n15    4 1996-05-05   Mic\n16    4 1999-03-12   Mic\n17    5 1993-10-09   Mac\n18    5 1997-01-28   Mac\n19    6 1993-08-17  Norm\n20    6 1996-02-16  Norm\n21    6 1998-07-17   Mic\n22    6 2004-05-28   Mac\n24    7 1994-01-16  Norm\n25    7 1995-07-09  Norm\n26    7 1999-03-22  Norm\n27    8 1994-05-14   Mac\n28    8 1996-10-11   Mac\n29    8 1997-12-25   Mac\n30    8 2003-10-05   Mac\n31    9 1993-07-10   Mic\n32   10 1994-09-26   Mac\n33   10 1995-10-30   Mac\n34   10 1998-01-30   Mac\n35   10 2004-08-30   Mac\n36   11 1994-07-12   Mic\n37   11 1996-12-23   Mac\n38   12 1994-09-25   Mic\n39   12 1995-05-02   Mic\n40   12 1998-11-17   Mac\n41   13 1993-12-25  Norm\n42   13 1996-01-12   Mic\n43   13 1998-11-21  Norm\n44   13 2002-04-05   Mic\n45   13 2014-08-14   Mic\n46   14 1993-07-14   Mic\n47   14 1996-05-07   Mic\n48   14 1997-11-30   Mic\n50   15 1994-05-15  Norm\n51   15 1995-06-28  Norm\n52   15 2000-07-12  Norm\n53   15 2002-11-09  Norm\n55   16 1994-07-16   Mic\n56   16 1996-11-27   Mic\n57   16 1997-03-27   Mac\n58   16 2004-04-15   Mic\n59   17 1993-09-08   Mic\n60   17 1996-11-09   Mic\n61   17 1999-10-20   Mac\n62   17 2006-09-12   Mic\n63   18 1994-07-08   Mic\n64   18 1995-01-18   Mic\n65   18 1998-02-01  Norm\n66   18 2006-06-05  Norm\n67   18 2013-10-18  Norm\n68   19 1994-02-09   Mic\n69   19 1997-02-03   Mic\n70   19 2001-03-15   Mic\n71   19 2001-09-20   Mac\n73   20 1994-09-18   Mac\n74   20 1995-03-13   Mic\n75   20 1998-11-01   Mic\n76   20 2001-02-12   Mic\n77   20 2008-12-24   Mac\n78   21 1994-04-29   Mic\n79   21 1996-12-15   Mac\n80   21 1998-05-01   Mic\n81   21 2006-01-26   Mic\n83   22 1993-06-09   Mic\n84   22 1995-11-16  Norm\n85   22 1997-09-05  Norm\n86   22 2004-02-06   Mic\n87   22 2007-01-15   Mic\n88   23 1994-12-30   Mac\n89   23 1996-10-16   Mac\n90   24 1993-09-25   Mic\n91   24 1996-07-23   Mic\n92   24 1999-09-09  Norm\n93   24 2005-06-07  Norm\n94   25 1994-01-11   Mic\n95   25 1997-01-09   Mic\n96   25 1997-06-02   Mic\n97   25 2002-01-05   Mic\n98   25 2008-10-22   Mac\n99   26 1994-02-17   Mic\n100  26 1995-06-14   Mic\n101  26 1999-10-03   Mac\n102  27 1995-03-01   Mic\n103  27 1995-09-09   Mic\n104  27 2000-06-02   Mic\n105  27 2005-05-06   Mic\n106  28 1993-12-21   Mac\n107  28 1996-12-26   Mac\n108  28 2000-04-05   Mic\n109  28 2003-04-21  Norm\n110  28 2007-12-08   Mic\n111  29 1993-12-20   Mic\n112  29 1996-06-28   Mac\n113  29 2000-10-17   Mac\n114  30 1993-12-14   Mic\n115  30 1995-08-30  Norm\n116  30 1999-06-24  Norm\n117  31 1994-10-03   Mic\n118  31 1996-05-15   Mic\n119  31 2001-03-03   Mic\n120  31 2001-09-04   Mac\n121  32 1994-07-13   Mac\n122  32 1996-04-27   Mic\n123  33 1994-08-02   Mic\n124  33 1995-05-01  Norm\n125  33 1997-08-27  Norm\n126  33 2005-05-28  Norm\n128  34 1993-05-28   Mic\n129  34 1996-11-13   Mic\n130  34 1998-07-23   Mic\n131  34 2002-04-14   Mac\n133  35 1995-02-12   Mic\n134  35 1995-06-22   Mic\n135  35 1999-07-25   Mac\n136  36 1994-10-01   Mic\n137  36 1995-02-02  Norm\n138  36 2001-06-06   Mic\n139  36 2002-03-22   Mic\n140  36 2013-07-28   Mic\n141  37 1993-10-06   Mic\n142  37 1996-02-06   Mic\n143  37 1998-05-17   Mic\n144  37 2004-04-09   Mic\n145  38 1994-02-23   Mac\n146  38 1995-11-16   Mic\n147  38 1999-09-13   Mac\n148  39 1993-09-25   Mic\n149  39 1996-11-16   Mic\n150  39 1998-06-10  Norm\n151  39 2001-11-17  Norm\n152  39 2006-10-26  Norm\n153  40 1994-09-03   Mic\n154  40 1996-05-12   Mic\n155  41 1994-09-01   Mic\n156  41 1997-04-18  Norm\n157  41 1998-07-07   Mic\n158  42 1995-02-16   Mic\n159  42 1995-08-08   Mic\n160  42 1997-09-07   Mic\n161  43 1993-11-24   Mac\n162  43 1995-08-27   Mic\n163  43 1998-02-05   Mac\n164  44 1994-06-23   Mic\n165  44 1996-09-28   Mic\n166  44 2000-06-01   Mic\n167  45 1993-12-24   Mic\n168  45 1996-04-14   Mic\n169  45 1998-08-17   Mac\n170  45 2002-04-01   Mic\n171  45 2009-10-22   Mic\n172  47 1993-06-06   Mic\n173  47 1997-01-09   Mic\n174  47 2000-08-07   Mic\n175  48 1993-09-02   Mic\n176  48 1996-01-15   Mic\n178  50 1995-02-20   Mic\n179  50 1995-06-11   Mic\n180  50 2001-01-28   Mac\n181  51 1994-03-27  Norm\n182  51 1995-07-17  Norm\n183  51 1999-05-23  Norm\n184  51 2001-04-14  Norm\n185  51 2010-07-12   Mic\n186  52 1993-12-19   Mic\n187  52 1995-12-11   Mic\n188  52 1997-10-03   Mic\n189  52 2003-02-28   Mic\n190  52 2009-10-26   Mic\n191  53 1993-04-21   Mac\n192  53 1996-07-29   Mic\n193  53 1999-05-07   Mac\n194  54 1994-06-09   Mic\n195  54 1996-10-14  Norm\n196  54 2000-10-11  Norm\n197  54 2003-09-10  Norm\n198  54 2008-05-10  Norm\n199  55 1995-01-08  Norm\n200  55 1995-09-05  Norm\n201  55 2000-04-09   Mic\n202  55 2005-08-27   Mic\n204  56 1993-11-11  Norm\n205  56 1996-05-17   Mic\n206  56 1998-10-21   Mic\n207  56 2004-08-19  Norm\n208  57 1993-11-09   Mac\n209  57 1996-01-22   Mic\n210  58 1994-10-26   Mic\n211  58 1997-01-13   Mic\n212  58 2001-01-04   Mic\n213  59 1993-11-19   Mac\n214  59 1997-09-01   Mac\n215  59 1998-02-25   Mac\n216  60 1993-12-26  Norm\n217  60 1996-05-26   Mic\n218  61 1994-09-25   Mac\n219  61 1995-05-08   Mac\n220  61 2001-03-24   Mac\n221  61 2005-03-18   Mic\n223  62 1993-07-25  Norm\n224  62 1995-10-20  Norm\n225  62 1998-04-13   Mic\n226  62 2001-06-07   Mac\n227  63 1994-02-16   Mac\n228  63 1997-02-07   Mac\n229  64 1994-07-09   Mic\n230  64 1995-12-12   Mic\n231  64 2000-01-01   Mic\n232  65 1994-08-28  Norm\n233  65 1995-09-20  Norm\n234  65 1999-09-30  Norm\n235  65 2001-04-29   Mic\n236  65 2012-07-05   Mic\n237  66 1994-04-15   Mic\n238  67 1993-10-11   Mic\n239  67 1995-10-12   Mac\n240  68 1995-10-07   Mic\n241  68 1997-04-12   Mic\n242  69 1993-09-19   Mic\n243  69 1996-06-27   Mic\n244  69 1998-03-12   Mic\n245  69 2003-06-11   Mic\n246  69 2012-01-09   Mic\n247  70 1994-04-15   Mic\n248  70 1996-06-17   Mic\n249  70 1999-06-28   Mac\n250  70 2002-03-01  Norm\n251  71 1994-02-27   Mic\n252  71 1995-11-03   Mic\n253  71 2000-10-04   Mic\n254  71 2005-11-14   Mic\n255  71 2013-07-14  Norm\n256  72 1995-03-04   Mic\n257  72 1996-09-16   Mic\n258  72 1999-04-28   Mic\n260  73 1993-05-02   Mic\n261  73 1997-07-24   Mic\n262  74 1995-03-09   Mic\n263  74 1997-05-02   Mic\n264  74 2000-02-21   Mac\n265  75 1993-12-08   Mic\n266  75 1997-04-26   Mic\n267  75 2001-02-04  Norm\n268  75 2002-10-17   Mic\n269  76 1993-10-18  Norm\n270  77 1993-05-20   Mic\n271  77 1996-10-31   Mic\n272  77 1998-10-21  Norm\n273  77 2001-07-28   Mic\n274  77 2012-12-10  Norm\n275  78 1993-12-10  Norm\n276  78 1995-11-03  Norm\n277  78 1998-04-10  Norm\n278  78 2005-03-12  Norm\n280  79 1994-04-24   Mic\n281  79 1995-08-03  Norm\n282  80 1993-11-04   Mic\n283  80 1996-10-01   Mic\n284  80 1999-10-05   Mic\n285  80 2006-02-16   Mic\n287  81 1994-11-20   Mic\n288  81 1996-01-31   Mic\n289  82 1993-05-17   Mic\n290  82 1995-08-19   Mic\n291  84 1993-09-13   Mic\n292  84 2004-09-28   Mac\n293  85 1993-10-02   Mic\n294  85 1995-11-30   Mic\n295  85 1997-06-24   Mac\n296  85 2004-05-27   Mac\n297  86 1993-12-06  Norm\n298  86 1996-01-15  Norm\n299  86 1997-11-10  Norm\n300  86 2001-10-05  Norm\n301  86 2014-07-30   Mac\n302  87 1994-04-05   Mic\n303  87 1996-08-23   Mic\n304  87 1997-09-07   Mac\n305  87 2002-05-17   Mac\n306  88 1995-03-06   Mic\n307  88 1995-11-30   Mic\n308  88 1998-07-27   Mic\n309  88 2004-04-18   Mic\n310  88 2011-10-16   Mac\n311  89 1993-12-12   Mic\n312  89 1997-02-03   Mic\n313  89 1999-01-17   Mic\n314  89 2004-07-02   Mic\n315  89 2008-01-27   Mic\n316  90 1995-06-21   Mic\n318  90 2000-03-22   Mac\n319  91 1994-03-26   Mic\n320  91 1996-05-02   Mic\n321  91 2000-11-29   Mic\n322  92 1994-09-01   Mic\n323  92 1996-01-02   Mic\n324  92 1998-08-12   Mic\n325  92 2003-11-10   Mic\n326  92 2012-06-19   Mac\n327  93 1993-10-19  Norm\n328  93 1996-12-10  Norm\n329  94 1995-03-23   Mic\n330  94 1995-11-04   Mic\n331  94 1999-01-01  Norm\n332  94 2002-02-03  Norm\n333  95 1995-01-20   Mic\n334  95 1996-09-13   Mic\n335  95 2000-01-26   Mic\n336  96 1994-02-08  Norm\n337  96 1996-09-07  Norm\n338  96 1998-08-03  Norm\n339  97 1994-06-10  Norm\n340  97 1996-02-24  Norm\n341  97 1998-05-20   Mic\n342  97 2002-01-19   Mic\n344  98 1994-12-11  Norm\n345  98 1995-09-03  Norm\n346  98 2000-09-12   Mic\n347  98 2002-07-26   Mic\n348 100 1995-01-12   Mic\n349 100 1996-11-28   Mic\n350 100 1999-02-19   Mic\n351 100 2004-02-08   Mic\n353 101 1995-06-10   Mic\n354 101 1996-08-16  Norm\n355 101 1999-01-26  Norm\n356 101 2001-11-25   Mic\n357 101 2010-06-29   Mac\n358 103 1993-10-17   Mic\n359 103 1996-05-22   Mic\n360 103 1998-09-25  Norm\n361 103 2004-05-18   Mic\n363 104 1994-12-05   Mic\n364 104 1995-11-10   Mic\n365 104 1999-08-20   Mic\n366 104 2005-12-19   Mac\n367 104 2009-01-21   Mac\n368 105 1994-03-29   Mic\n369 105 1995-10-28   Mic\n370 105 1997-09-28   Mic\n371 105 2005-01-26   Mic\n372 105 2012-10-09   Mic\n373 107 1994-08-29   Mic\n374 107 1996-12-20   Mic\n375 107 1997-10-31  Norm\n376 108 1994-11-07  Norm\n377 108 1995-10-10  Norm\n378 108 1998-12-12  Norm\n379 108 2005-01-26   Mic\n380 108 2011-05-19  Norm\n381 110 1994-02-16   Mic\n382 110 1996-04-28  Norm\n383 110 1999-08-26  Norm\n384 110 2003-12-08   Mic\n385 111 1995-02-26   Mic\n386 111 1996-04-23   Mic\n387 111 1998-10-01  Norm\n388 111 2001-09-28  Norm\n389 111 2007-07-21  Norm\n390 112 1993-10-09   Mic\n391 112 1996-09-21   Mic\n392 112 1998-04-28   Mic\n393 112 2004-07-29   Mic\n394 112 2011-12-18   Mic\n395 113 1994-12-12   Mic\n396 113 1996-04-02  Norm\n397 114 1994-07-25   Mic\n398 114 1996-03-07   Mic\n399 114 2000-08-11   Mic\n400 115 1995-07-05  Norm\n401 115 1997-02-25  Norm\n402 115 1998-09-07  Norm\n403 115 2002-07-16  Norm\n404 115 2009-02-21  Norm\n405 116 1994-02-23   Mic\n406 116 1997-01-01   Mic\n407 116 1997-09-06   Mic\n408 118 1995-06-17   Mic\n409 118 1996-12-29   Mac\n410 118 1997-11-08   Mac\n411 119 1994-06-22  Norm\n412 119 1996-11-12  Norm\n413 120 1994-01-19   Mic\n414 120 1996-05-28   Mic\n415 120 1999-03-04  Norm\n416 121 1994-05-24   Mic\n417 121 1996-06-11   Mac\n418 121 2000-07-24   Mac\n419 121 2005-08-03   Mic\n420 123 1995-02-12   Mic\n421 123 1996-11-16   Mic\n422 123 1998-09-28  Norm\n423 123 2004-11-21   Mic\n424 123 2006-12-04  Norm\n425 126 1994-12-13   Mic\n426 126 1997-01-14   Mic\n427 126 1998-06-24   Mic\n428 126 2003-01-21   Mic\n429 126 2012-01-06   Mic\n431 129 1995-07-02   Mic\n432 129 1997-08-19   Mic\n433 129 1998-07-12  Norm\n434 130 1994-06-09   Mic\n435 130 1996-07-18   Mic\n436 130 2000-11-29   Mac\n437 130 2002-10-16  Norm\n438 131 1995-08-11  Norm\n439 131 1997-05-05  Norm\n440 131 1997-10-04  Norm\n441 131 2001-12-29   Mac\n442 133 1995-09-29  Norm\n444 133 1998-09-23  Norm\n445 133 2003-01-01  Norm\n446 134 1994-09-27   Mic\n447 135 1995-03-16   Mic\n448 135 1996-03-26   Mic\n449 135 1999-02-25   Mic\n450 136 1995-08-17   Mic\n451 136 1997-03-20   Mac\n452 136 1997-09-08  Norm\n453 136 2001-12-06   Mac\n454 137 1995-07-13  Norm\n455 137 1995-11-22  Norm\n456 138 1994-06-27  Norm\n457 138 1997-03-28  Norm\n458 138 1997-06-25  Norm\n459 138 2004-03-25  Norm\n460 138 2009-05-13  Norm\n461 139 1995-07-07   Mic\n462 139 1996-09-30   Mic\n463 140 1994-10-24   Mic\n464 140 1995-10-26  Norm\n465 140 1999-06-04  Norm\n467 140 2008-08-12   Mic\n468 142 1995-08-05   Mic\n469 142 1995-09-13   Mic\n470 142 2001-08-03   Mic\n471 142 2002-03-03   Mic\n472 143 1993-12-31   Mac\n473 143 1996-05-07   Mic\n474 143 1999-06-01  Norm\n475 144 1994-10-09   Mic\n476 144 1996-03-10   Mic\n477 144 2001-03-29   Mic\n478 144 2005-11-30   Mic\n479 145 1995-03-23   Mic\n480 145 1997-07-17  Norm\n481 146 1994-12-13   Mic\n482 146 1997-06-08  Norm\n483 147 1994-08-05   Mic\n484 147 1996-08-16   Mic\n485 147 2007-05-21   Mic\n486 148 1995-02-21   Mic\n487 148 1996-02-01   Mac\n488 148 1998-09-05   Mic\n489 148 2003-01-17  Norm\n491 151 1995-05-10   Mic\n492 151 1997-06-12   Mac\n493 151 1998-05-09   Mac\n494 152 1994-10-31   Mic\n495 152 1996-05-26   Mic\n496 152 2000-06-22   Mic\n497 152 2003-11-23   Mic\n498 152 2009-03-19   Mic\n499 153 1994-05-08   Mac\n500 153 1997-04-18   Mac\n501 153 1999-09-13   Mic\n502 155 1995-02-07   Mic\n503 155 1997-01-07   Mac\n504 155 2000-03-22   Mic\n505 155 2005-05-17   Mac\n506 155 2007-06-20   Mac\n507 156 1995-06-23   Mic\n508 156 1997-07-30   Mic\n509 156 1998-12-06   Mic\n510 156 2001-10-05   Mic\n511 156 2010-12-26   Mac\n512 157 1994-05-16   Mic\n513 157 1996-02-21   Mac\n514 157 2006-10-26   Mac\n515 158 1995-04-07   Mic\n516 158 1997-09-19   Mic\n517 158 2001-02-04   Mac\n518 158 2005-09-20   Mic\n519 159 1994-02-28   Mic\n520 159 1996-10-28  Norm\n521 159 1999-03-14   Mic\n522 159 2006-07-09   Mac\n523 160 1994-10-15   Mic\n524 160 1996-06-06  Norm\n525 161 1995-05-03   Mic\n526 161 1995-12-21   Mic\n527 161 1999-03-08   Mic\n528 161 2003-07-10   Mic\n529 161 2013-01-28   Mac\n530 163 1994-12-20   Mic\n531 163 1996-12-18   Mac\n532 163 2000-04-21   Mac\n533 165 1995-01-29  Norm\n534 165 1996-01-01  Norm\n535 165 1999-09-20   Mic\n536 166 1994-12-05   Mic\n537 166 1996-07-01   Mic\n538 166 2000-03-17  Norm\n539 166 2003-01-16   Mic\n540 167 1994-03-30  Norm\n541 167 1996-04-29  Norm\n542 167 1998-05-16  Norm\n543 167 2006-06-29  Norm\n544 167 2010-08-28  Norm\n545 168 1994-03-19   Mic\n546 168 1996-04-17   Mac\n547 168 1999-07-17   Mac\n548 168 2003-04-10   Mac\n550 169 1995-05-02   Mic\n551 169 1995-12-18  Norm\n552 169 1998-08-24  Norm\n553 169 2005-10-28   Mic\n554 169 2013-05-23   Mic\n555 170 1994-09-07   Mic\n556 170 1997-04-03  Norm\n557 170 2000-02-07  Norm\n558 170 2006-01-09   Mic\n560 171 1994-10-09   Mic\n561 171 1996-05-23  Norm\n562 171 2001-09-24   Mac\n563 171 2004-08-24   Mac\n564 171 2011-04-13   Mic\n565 172 1994-06-23   Mic\n566 172 1996-02-12   Mic\n567 172 1998-04-02   Mac\n568 172 2002-02-23   Mac\n569 173 1995-04-26  Norm\n570 173 1996-06-12  Norm\n571 173 1999-11-21  Norm\n572 173 2002-09-08  Norm\n574 174 1995-02-05   Mic\n576 174 2000-07-25   Mic\n577 174 2003-04-10   Mic\n578 174 2009-04-16   Mic\n579 175 1994-09-19   Mic\n580 175 1997-02-27   Mic\n581 175 1998-10-13   Mic\n582 175 2004-08-02  Norm\n583 175 2014-06-21   Mac\n584 176 1994-11-10  Norm\n585 176 1997-02-08  Norm\n586 176 1998-12-07  Norm\n587 176 2005-09-17  Norm\n588 176 2013-05-22  Norm\n```\n\n\n:::\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[[1]]\n  records max_id\n1     160    176\n\n[[2]]\n  records max_id\n1     160    176\n\n[[3]]\n  records max_id\n1     156    176\n```\n\n\n:::\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[[1]]\n   id allo sex baseCVD deathCVD      doBth       doDM     doBase     doCVD1\n1  83  Int   M       0        1 1930-12-23 1989-06-28 1992-12-22 1994-12-04\n2 102  Int   M       0        1 1935-04-09 1990-03-19 1993-07-17 1995-04-23\n3 128 Conv   M       0        0 1937-03-14 1989-02-16 1993-10-03 1995-11-13\n4 150 Conv   F       0        0 1946-02-18 1989-10-29 1993-12-24       <NA>\n      doCVD2     doCVD3     doESRD      doEnd      doDth\n1 1994-12-12       <NA>        NaN 1994-11-15 1994-12-19\n2       <NA>       <NA>        NaN 1995-03-30 1995-05-02\n3 2003-08-07 2004-05-31 1999-12-26 2005-05-19 2005-05-18\n4       <NA>       <NA>        NaN 2014-08-27       <NA>\n\n[[2]]\n [1] id       allo     sex      baseCVD  deathCVD doBth    doDM     doBase  \n [9] doCVD1   doCVD2   doCVD3   doESRD   doEnd    doDth   \n<0 rows> (or 0-length row.names)\n```\n\n\n:::\n\n::: {.cell-output .cell-output-stdout}\n\n```\n       id           allo    sex        baseCVD          deathCVD     \n Min.   :  1.00   Int :80   F: 41   Min.   :0.0000   Min.   :0.0000  \n 1st Qu.: 40.75   Conv:80   M:119   1st Qu.:0.0000   1st Qu.:0.0000  \n Median : 82.50                     Median :0.0000   Median :0.0000  \n Mean   : 85.31                     Mean   :0.1375   Mean   :0.2375  \n 3rd Qu.:130.25                     3rd Qu.:0.0000   3rd Qu.:0.0000  \n Max.   :176.00                     Max.   :1.0000   Max.   :1.0000  \n                                                                     \n     doBth                 doDM                doBase          \n Min.   :1926-07-13   Min.   :1962-06-21   Min.   :1992-12-22  \n 1st Qu.:1932-07-18   1st Qu.:1982-10-01   1st Qu.:1993-03-23  \n Median :1937-03-12   Median :1987-05-02   Median :1993-06-11  \n Mean   :1938-06-03   Mean   :1986-01-15   Mean   :1993-07-22  \n 3rd Qu.:1944-11-28   3rd Qu.:1990-05-03   3rd Qu.:1993-11-15  \n Max.   :1956-04-07   Max.   :1994-02-07   Max.   :1994-06-14  \n                                                               \n     doCVD1               doCVD2               doCVD3          \n Min.   :1993-03-17   Min.   :1994-08-05   Min.   :1995-12-16  \n 1st Qu.:1997-02-16   1st Qu.:1999-04-18   1st Qu.:2001-11-23  \n Median :2001-04-03   Median :2002-12-20   Median :2004-12-13  \n Mean   :2001-12-18   Mean   :2003-10-04   Mean   :2005-01-11  \n 3rd Qu.:2006-07-20   3rd Qu.:2008-07-20   3rd Qu.:2009-06-03  \n Max.   :2014-05-30   Max.   :2014-03-26   Max.   :2012-07-21  \n NA's   :41           NA's   :84           NA's   :117         \n     doESRD               doEnd                doDth           \n Min.   :1998-02-18   Min.   :1994-11-16   Min.   :1994-12-19  \n 1st Qu.:2002-09-25   1st Qu.:2002-09-18   1st Qu.:2000-05-21  \n Median :2008-05-08   Median :2010-02-11   Median :2004-03-06  \n Mean   :2006-07-17   Mean   :2008-08-29   Mean   :2004-05-24  \n 3rd Qu.:2009-07-29   3rd Qu.:2014-09-25   3rd Qu.:2009-06-04  \n Max.   :2014-07-07   Max.   :2014-12-31   Max.   :2014-02-16  \n NA's   :145                               NA's   :67          \n```\n\n\n:::\n\n::: {.cell-output .cell-output-stderr}\n\n```\n`stat_bin()` using `bins = 30`. Pick better value with `binwidth`.\n```\n\n\n:::\n\n::: {.cell-output .cell-output-stderr}\n\n```\nWarning: Removed 454 rows containing non-finite outside the scale range\n(`stat_bin()`).\n```\n\n\n:::\n\n::: {.cell-output-display}\n![](index_files/figure-html/summary-1.png){width=768}\n:::\n\n::: {.cell-output .cell-output-stderr}\n\n```\n`stat_bin()` using `bins = 30`. Pick better value with `binwidth`.\n```\n\n\n:::\n\n::: {.cell-output .cell-output-stderr}\n\n```\nWarning: Removed 454 rows containing non-finite outside the scale range\n(`stat_bin()`).\n```\n\n\n:::\n\n::: {.cell-output-display}\n![](index_files/figure-html/summary-2.png){width=768}\n:::\n\n::: {.cell-output .cell-output-stderr}\n\n```\n`stat_bin()` using `bins = 30`. Pick better value with `binwidth`.\n```\n\n\n:::\n\n::: {.cell-output .cell-output-stderr}\n\n```\nWarning: Removed 454 rows containing non-finite outside the scale range\n(`stat_bin()`).\n```\n\n\n:::\n\n::: {.cell-output-display}\n![](index_files/figure-html/summary-3.png){width=768}\n:::\n\n::: {.cell-output-display}\n![](index_files/figure-html/summary-4.png){width=768}\n:::\n\n::: {.cell-output-display}\n![](index_files/figure-html/summary-5.png){width=768}\n:::\n\n::: {.cell-output .cell-output-stdout}\n\n```\nCall: survfit(formula = Surv(time_yrs, event_num) ~ 1, data = steno2)\n\n time n.risk n.event survival std.err lower 95% CI upper 95% CI\n    0    160       0    1.000 0.00000        1.000        1.000\n    1    160       0    1.000 0.00000        1.000        1.000\n    2    158       2    0.988 0.00878        0.970        1.000\n    3    155       3    0.969 0.01376        0.942        0.996\n    4    154       1    0.963 0.01502        0.934        0.992\n    5    148       6    0.925 0.02082        0.885        0.967\n    6    143       5    0.894 0.02436        0.847        0.943\n    7    137       6    0.856 0.02774        0.804        0.912\n    8    131       6    0.819 0.03045        0.761        0.881\n    9    125       6    0.781 0.03268        0.720        0.848\n   10    116       9    0.725 0.03530        0.659        0.798\nCall: survfit(formula = Surv(time_yrs, event_num) ~ allo, data = steno2)\n\n                allo=Int \n time n.risk n.event survival std.err lower 95% CI upper 95% CI\n    0     80       0    1.000  0.0000        1.000        1.000\n    1     80       0    1.000  0.0000        1.000        1.000\n    2     78       2    0.975  0.0175        0.941        1.000\n    3     77       1    0.963  0.0212        0.922        1.000\n    4     76       1    0.950  0.0244        0.903        0.999\n    5     75       1    0.938  0.0271        0.886        0.992\n    6     73       2    0.913  0.0316        0.853        0.977\n    7     70       3    0.875  0.0370        0.805        0.951\n    8     66       4    0.825  0.0425        0.746        0.913\n    9     64       2    0.800  0.0447        0.717        0.893\n   10     63       1    0.788  0.0457        0.703        0.882\n\n                allo=Conv \n time n.risk n.event survival std.err lower 95% CI upper 95% CI\n    0     80       0    1.000  0.0000        1.000        1.000\n    1     80       0    1.000  0.0000        1.000        1.000\n    2     80       0    1.000  0.0000        1.000        1.000\n    3     78       2    0.975  0.0175        0.941        1.000\n    4     78       0    0.975  0.0175        0.941        1.000\n    5     73       5    0.913  0.0316        0.853        0.977\n    6     70       3    0.875  0.0370        0.805        0.951\n    7     67       3    0.838  0.0412        0.760        0.922\n    8     65       2    0.813  0.0436        0.731        0.903\n    9     61       4    0.763  0.0476        0.675        0.862\n   10     53       8    0.663  0.0529        0.567        0.775\n\nCall: survfit(formula = Surv(time_yrs, event_num) ~ sex, data = steno2)\n\n                sex=F \n time n.risk n.event survival std.err lower 95% CI upper 95% CI\n    0     41       0    1.000  0.0000        1.000        1.000\n    1     41       0    1.000  0.0000        1.000        1.000\n    2     41       0    1.000  0.0000        1.000        1.000\n    3     40       1    0.976  0.0241        0.930        1.000\n    4     40       0    0.976  0.0241        0.930        1.000\n    5     40       0    0.976  0.0241        0.930        1.000\n    6     39       1    0.951  0.0336        0.888        1.000\n    7     37       2    0.902  0.0463        0.816        0.998\n    8     34       3    0.829  0.0588        0.722        0.953\n    9     31       3    0.756  0.0671        0.635        0.900\n   10     29       2    0.707  0.0711        0.581        0.861\n\n                sex=M \n time n.risk n.event survival std.err lower 95% CI upper 95% CI\n    0    119       0    1.000  0.0000        1.000        1.000\n    1    119       0    1.000  0.0000        1.000        1.000\n    2    117       2    0.983  0.0118        0.960        1.000\n    3    115       2    0.966  0.0165        0.935        0.999\n    4    114       1    0.958  0.0184        0.923        0.995\n    5    108       6    0.908  0.0266        0.857        0.961\n    6    104       4    0.874  0.0304        0.816        0.936\n    7    100       4    0.840  0.0336        0.777        0.909\n    8     97       3    0.815  0.0356        0.748        0.888\n    9     94       3    0.790  0.0373        0.720        0.867\n   10     87       7    0.731  0.0406        0.656        0.815\n\nCall: survfit(formula = Surv(time_yrs, event_num) ~ allo + sex, data = steno2)\n\n                allo=Int, sex=F \n time n.risk n.event survival std.err lower 95% CI upper 95% CI\n    0     17       0    1.000  0.0000        1.000            1\n    1     17       0    1.000  0.0000        1.000            1\n    2     17       0    1.000  0.0000        1.000            1\n    3     17       0    1.000  0.0000        1.000            1\n    4     17       0    1.000  0.0000        1.000            1\n    5     17       0    1.000  0.0000        1.000            1\n    6     17       0    1.000  0.0000        1.000            1\n    7     17       0    1.000  0.0000        1.000            1\n    8     15       2    0.882  0.0781        0.742            1\n    9     14       1    0.824  0.0925        0.661            1\n   10     14       0    0.824  0.0925        0.661            1\n\n                allo=Int, sex=M \n time n.risk n.event survival std.err lower 95% CI upper 95% CI\n    0     63       0    1.000  0.0000        1.000        1.000\n    1     63       0    1.000  0.0000        1.000        1.000\n    2     61       2    0.968  0.0221        0.926        1.000\n    3     60       1    0.952  0.0268        0.901        1.000\n    4     59       1    0.937  0.0307        0.878        0.999\n    5     58       1    0.921  0.0341        0.856        0.990\n    6     56       2    0.889  0.0396        0.815        0.970\n    7     53       3    0.841  0.0460        0.756        0.937\n    8     51       2    0.810  0.0495        0.718        0.913\n    9     50       1    0.794  0.0510        0.700        0.900\n   10     49       1    0.778  0.0524        0.682        0.888\n\n                allo=Conv, sex=F \n time n.risk n.event survival std.err lower 95% CI upper 95% CI\n    0     24       0    1.000  0.0000        1.000        1.000\n    1     24       0    1.000  0.0000        1.000        1.000\n    2     24       0    1.000  0.0000        1.000        1.000\n    3     23       1    0.958  0.0408        0.882        1.000\n    4     23       0    0.958  0.0408        0.882        1.000\n    5     23       0    0.958  0.0408        0.882        1.000\n    6     22       1    0.917  0.0564        0.813        1.000\n    7     20       2    0.833  0.0761        0.697        0.997\n    8     19       1    0.792  0.0829        0.645        0.972\n    9     17       2    0.708  0.0928        0.548        0.916\n   10     15       2    0.625  0.0988        0.458        0.852\n\n                allo=Conv, sex=M \n time n.risk n.event survival std.err lower 95% CI upper 95% CI\n    0     56       0    1.000  0.0000        1.000        1.000\n    1     56       0    1.000  0.0000        1.000        1.000\n    2     56       0    1.000  0.0000        1.000        1.000\n    3     55       1    0.982  0.0177        0.948        1.000\n    4     55       0    0.982  0.0177        0.948        1.000\n    5     50       5    0.893  0.0413        0.815        0.978\n    6     48       2    0.857  0.0468        0.770        0.954\n    7     47       1    0.839  0.0491        0.748        0.941\n    8     46       1    0.821  0.0512        0.727        0.928\n    9     44       2    0.786  0.0548        0.685        0.901\n   10     38       6    0.679  0.0624        0.567        0.813\n```\n\n\n:::\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[[1]]\nCall: survfit(formula = Surv(time_yrs, event_num) ~ 1, data = steno2)\n\n time n.risk n.event survival std.err lower 95% CI upper 95% CI\n    0    160       0    1.000 0.00000        1.000        1.000\n    1    160       0    1.000 0.00000        1.000        1.000\n    2    158       2    0.988 0.00878        0.970        1.000\n    3    155       3    0.969 0.01376        0.942        0.996\n    4    154       1    0.963 0.01502        0.934        0.992\n    5    148       6    0.925 0.02082        0.885        0.967\n    6    143       5    0.894 0.02436        0.847        0.943\n    7    137       6    0.856 0.02774        0.804        0.912\n    8    131       6    0.819 0.03045        0.761        0.881\n    9    125       6    0.781 0.03268        0.720        0.848\n   10    116       9    0.725 0.03530        0.659        0.798\n\n[[2]]\nCall: survfit(formula = Surv(time_yrs, event_num) ~ allo, data = steno2)\n\n                allo=Int \n time n.risk n.event survival std.err lower 95% CI upper 95% CI\n    0     80       0    1.000  0.0000        1.000        1.000\n    1     80       0    1.000  0.0000        1.000        1.000\n    2     78       2    0.975  0.0175        0.941        1.000\n    3     77       1    0.963  0.0212        0.922        1.000\n    4     76       1    0.950  0.0244        0.903        0.999\n    5     75       1    0.938  0.0271        0.886        0.992\n    6     73       2    0.913  0.0316        0.853        0.977\n    7     70       3    0.875  0.0370        0.805        0.951\n    8     66       4    0.825  0.0425        0.746        0.913\n    9     64       2    0.800  0.0447        0.717        0.893\n   10     63       1    0.788  0.0457        0.703        0.882\n\n                allo=Conv \n time n.risk n.event survival std.err lower 95% CI upper 95% CI\n    0     80       0    1.000  0.0000        1.000        1.000\n    1     80       0    1.000  0.0000        1.000        1.000\n    2     80       0    1.000  0.0000        1.000        1.000\n    3     78       2    0.975  0.0175        0.941        1.000\n    4     78       0    0.975  0.0175        0.941        1.000\n    5     73       5    0.913  0.0316        0.853        0.977\n    6     70       3    0.875  0.0370        0.805        0.951\n    7     67       3    0.838  0.0412        0.760        0.922\n    8     65       2    0.813  0.0436        0.731        0.903\n    9     61       4    0.763  0.0476        0.675        0.862\n   10     53       8    0.663  0.0529        0.567        0.775\n\n\n[[3]]\nCall: survfit(formula = Surv(time_yrs, event_num) ~ sex, data = steno2)\n\n                sex=F \n time n.risk n.event survival std.err lower 95% CI upper 95% CI\n    0     41       0    1.000  0.0000        1.000        1.000\n    1     41       0    1.000  0.0000        1.000        1.000\n    2     41       0    1.000  0.0000        1.000        1.000\n    3     40       1    0.976  0.0241        0.930        1.000\n    4     40       0    0.976  0.0241        0.930        1.000\n    5     40       0    0.976  0.0241        0.930        1.000\n    6     39       1    0.951  0.0336        0.888        1.000\n    7     37       2    0.902  0.0463        0.816        0.998\n    8     34       3    0.829  0.0588        0.722        0.953\n    9     31       3    0.756  0.0671        0.635        0.900\n   10     29       2    0.707  0.0711        0.581        0.861\n\n                sex=M \n time n.risk n.event survival std.err lower 95% CI upper 95% CI\n    0    119       0    1.000  0.0000        1.000        1.000\n    1    119       0    1.000  0.0000        1.000        1.000\n    2    117       2    0.983  0.0118        0.960        1.000\n    3    115       2    0.966  0.0165        0.935        0.999\n    4    114       1    0.958  0.0184        0.923        0.995\n    5    108       6    0.908  0.0266        0.857        0.961\n    6    104       4    0.874  0.0304        0.816        0.936\n    7    100       4    0.840  0.0336        0.777        0.909\n    8     97       3    0.815  0.0356        0.748        0.888\n    9     94       3    0.790  0.0373        0.720        0.867\n   10     87       7    0.731  0.0406        0.656        0.815\n\n\n[[4]]\nCall: survfit(formula = Surv(time_yrs, event_num) ~ allo + sex, data = steno2)\n\n                allo=Int, sex=F \n time n.risk n.event survival std.err lower 95% CI upper 95% CI\n    0     17       0    1.000  0.0000        1.000            1\n    1     17       0    1.000  0.0000        1.000            1\n    2     17       0    1.000  0.0000        1.000            1\n    3     17       0    1.000  0.0000        1.000            1\n    4     17       0    1.000  0.0000        1.000            1\n    5     17       0    1.000  0.0000        1.000            1\n    6     17       0    1.000  0.0000        1.000            1\n    7     17       0    1.000  0.0000        1.000            1\n    8     15       2    0.882  0.0781        0.742            1\n    9     14       1    0.824  0.0925        0.661            1\n   10     14       0    0.824  0.0925        0.661            1\n\n                allo=Int, sex=M \n time n.risk n.event survival std.err lower 95% CI upper 95% CI\n    0     63       0    1.000  0.0000        1.000        1.000\n    1     63       0    1.000  0.0000        1.000        1.000\n    2     61       2    0.968  0.0221        0.926        1.000\n    3     60       1    0.952  0.0268        0.901        1.000\n    4     59       1    0.937  0.0307        0.878        0.999\n    5     58       1    0.921  0.0341        0.856        0.990\n    6     56       2    0.889  0.0396        0.815        0.970\n    7     53       3    0.841  0.0460        0.756        0.937\n    8     51       2    0.810  0.0495        0.718        0.913\n    9     50       1    0.794  0.0510        0.700        0.900\n   10     49       1    0.778  0.0524        0.682        0.888\n\n                allo=Conv, sex=F \n time n.risk n.event survival std.err lower 95% CI upper 95% CI\n    0     24       0    1.000  0.0000        1.000        1.000\n    1     24       0    1.000  0.0000        1.000        1.000\n    2     24       0    1.000  0.0000        1.000        1.000\n    3     23       1    0.958  0.0408        0.882        1.000\n    4     23       0    0.958  0.0408        0.882        1.000\n    5     23       0    0.958  0.0408        0.882        1.000\n    6     22       1    0.917  0.0564        0.813        1.000\n    7     20       2    0.833  0.0761        0.697        0.997\n    8     19       1    0.792  0.0829        0.645        0.972\n    9     17       2    0.708  0.0928        0.548        0.916\n   10     15       2    0.625  0.0988        0.458        0.852\n\n                allo=Conv, sex=M \n time n.risk n.event survival std.err lower 95% CI upper 95% CI\n    0     56       0    1.000  0.0000        1.000        1.000\n    1     56       0    1.000  0.0000        1.000        1.000\n    2     56       0    1.000  0.0000        1.000        1.000\n    3     55       1    0.982  0.0177        0.948        1.000\n    4     55       0    0.982  0.0177        0.948        1.000\n    5     50       5    0.893  0.0413        0.815        0.978\n    6     48       2    0.857  0.0468        0.770        0.954\n    7     47       1    0.839  0.0491        0.748        0.941\n    8     46       1    0.821  0.0512        0.727        0.928\n    9     44       2    0.786  0.0548        0.685        0.901\n   10     38       6    0.679  0.0624        0.567        0.813\n```\n\n\n:::\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[[1]]\n```\n\n\n:::\n\n::: {.cell-output-display}\n![](index_files/figure-html/summary-6.png){width=768}\n:::\n\n::: {.cell-output .cell-output-stdout}\n\n```\n\n[[2]]\n```\n\n\n:::\n\n::: {.cell-output-display}\n![](index_files/figure-html/summary-7.png){width=768}\n:::\n\n::: {.cell-output .cell-output-stdout}\n\n```\n\n[[3]]\n```\n\n\n:::\n\n::: {.cell-output-display}\n![](index_files/figure-html/summary-8.png){width=768}\n:::\n\n::: {.cell-output .cell-output-stdout}\n\n```\n\n[[4]]\n```\n\n\n:::\n\n::: {.cell-output-display}\n![](index_files/figure-html/summary-9.png){width=768}\n:::\n\n\n::: {.cell-output-display}\n![](index_files/figure-html/summary-10.png){width=768}\n:::\n\n::: {.cell-output .cell-output-stderr}\n\n```\nWarning in geom_segment(aes(x = 0, y = max(y2), xend = max(x1), yend = max(y2)), : All aesthetics have length 1, but the data has 3 rows.\nℹ Please consider using `annotate()` or provide this layer with data containing\n  a single row.\n```\n\n\n:::\n\n::: {.cell-output .cell-output-stderr}\n\n```\nWarning in geom_segment(aes(x = 0, y = max(y2), xend = max(x1), yend = max(y2)), : All aesthetics have length 1, but the data has 3 rows.\nℹ Please consider using `annotate()` or provide this layer with data containing\n  a single row.\nAll aesthetics have length 1, but the data has 3 rows.\nℹ Please consider using `annotate()` or provide this layer with data containing\n  a single row.\nAll aesthetics have length 1, but the data has 3 rows.\nℹ Please consider using `annotate()` or provide this layer with data containing\n  a single row.\n```\n\n\n:::\n\n::: {.cell-output-display}\n![](index_files/figure-html/summary-11.png){width=768}\n:::\n\n::: {.cell-output .cell-output-stdout}\n\n```\nCall:\nsurvdiff(formula = Surv(time_yrs, event_num) ~ allo, data = steno2)\n\n           N Observed Expected (O-E)^2/E (O-E)^2/V\nallo=Int  80       38     51.7      3.64      8.29\nallo=Conv 80       55     41.3      4.56      8.29\n\n Chisq= 8.3  on 1 degrees of freedom, p= 0.004 \n```\n\n\n:::\n\n::: {.cell-output .cell-output-stdout}\n\n```\nCall:\nsurvdiff(formula = Surv(time_yrs, event_num) ~ sex, data = steno2)\n\n        N Observed Expected (O-E)^2/E (O-E)^2/V\nsex=F  41       20     25.5     1.182      1.63\nsex=M 119       73     67.5     0.446      1.63\n\n Chisq= 1.6  on 1 degrees of freedom, p= 0.2 \n```\n\n\n:::\n\n::: {.cell-output-display}\n![](index_files/figure-html/summary-12.png){width=768}\n:::\n\n::: {.cell-output-display}\n![](index_files/figure-html/summary-13.png){width=768}\n:::\n\n::: {.cell-output .cell-output-stdout}\n\n```\n# A tibble: 4 × 8\n  model term     estimate std.error statistic p.value conf.low conf.high\n  <chr> <chr>       <dbl>     <dbl>     <dbl>   <dbl>    <dbl>     <dbl>\n1 allo  alloConv    0.602     0.212      2.84 0.00455    0.186     1.02 \n2 sex   sexM        0.321     0.253      1.27 0.203     -0.174     0.816\n3 both  alloConv    0.628     0.213      2.95 0.00316    0.211     1.05 \n4 both  sexM        0.379     0.253      1.50 0.135     -0.118     0.875\n```\n\n\n:::\n\n::: {.cell-output .cell-output-stdout}\n\n```\n# A tibble: 4 × 8\n  model term     estimate std.error statistic p.value conf.low conf.high\n  <chr> <chr>       <dbl>     <dbl>     <dbl>   <dbl>    <dbl>     <dbl>\n1 allo  alloConv     1.83     0.212      2.84 0.00455    1.20       2.77\n2 sex   sexM         1.38     0.253      1.27 0.203      0.840      2.26\n3 both  alloConv     1.87     0.213      2.95 0.00316    1.23       2.84\n4 both  sexM         1.46     0.253      1.50 0.135      0.889      2.40\n```\n\n\n:::\n\n::: {.cell-output .cell-output-stdout}\n\n```\n# A tibble: 2 × 3\n  allo  .fitted .se.fit\n  <chr>   <dbl>   <dbl>\n1 Conv     1.83   0.287\n2 Int      1      0    \n```\n\n\n:::\n\n::: {.cell-output .cell-output-stdout}\n\n```\n# A tibble: 4 × 4\n  allo  sex   .fitted .se.fit\n  <fct> <fct>   <dbl>   <dbl>\n1 Conv  M        2.74   0.567\n2 Int   M        1.46   0.306\n3 Conv  F        1.87   0.291\n4 Int   F        1      0    \n```\n\n\n:::\n:::\n\n",
    "supporting": [
      "index_files"
    ],
    "filters": [
      "rmarkdown/pagebreak.lua"
    ],
    "includes": {},
    "engineDependencies": {},
    "preserve": {},
    "postProcess": true
  }
}