---
title: "Welcome"
format:
  html:
    css: styles.css
    page-layout: full
    #mermaid:
    #  theme: forest
---

<!-- TODO for me

- [ ] Finish ADAM post
- [ ] Parameterised Quarto reports in R
- [ ] Do a blog post on how ridiculous AI is at making testable R chunks (see playground\swimplot.R, but start on your own and take time of how long it takes to create 5 different tests i make up on the spot).

-->

<!-- <div class="fullpage-mermaid"> -->

```{mermaid}
%%| fig-label: YAY
flowchart TB
  A[Studying Medicine with Industrial Specialisation]
  A2[Study of <br/>Medicine]
  A3[Study of <br/>Healthcare systems <br/> Health economics <br/>Quality improvement]
  %%B[Volunteer work]
  C[Research assistant]
  D[PhD in<br/><i/>Diabetes Epidemiology and Health Economics<b>]
  E1[Data analyst/science work<br/><i/>R, Stata, Excel, SAS<b>]
  E2[Extensive experience with Systematic Reviewing]
  E3[Data Visualisation <br/>Theoretical assumption testing with real-world data]
  F[Uncovering insights using Health Data to <br/> - Learn and understand how to translate data into action <br/> - Improve Quality of Healthcare ]

  A --> A2
  A --> A3
  A2 --> C
  A3 --> C
  C --> D
  D --> E1
  D --> E2
  D --> E3

  E1 --> F
  E2 --> F
  E3 --> F
  %%B --> F

```

<!-- </div> -->

## Summary of wepbage

Welcome to my webpage. This can be considered by portfolio and playground. After a family-centered hiatus from working, I am picking up the torch again.

My journey from studying at university, to finishing a PhD, has lead me here. The combination of R/Quarto/Github is a wonderfully easy and customisable thing to test my skills and learn more.

**My one goal right now is figuring out how I can coalesce all my skills for the benefit of the Danish healthcare system, future colleagues, and patients.**

## Who am I

I'm a:

- Father and husband
- Data lover
- People helper
- Learner
- Explorer of connections and correlations
- Tester of theories versus the real world
- Deep thinker and systematiser
- Pragmatic solution enthusiast

## AI

You might wonder why I have a section on AI here. The reason is simple:

- If you don't use it, you will fall behind
- If you use it thoughtlessly, you will produce garbage

I am a firm believer that current AI use is contrasted in two concomitantly existing extremes:

1. Underused
   - one of the most useful tools humanity has invented, hailed as "the great equalizer" for good reason
   - most people I have worked with are just catching up and using it for stuff I used it for 2 years ago
2. Overused
   - prone to a bubble bursting soon
   - thoughtlessly used for almost everything
   - potentially limiting human thinking and flourishing

**As such, I will explicitly state when I use AI.**

You have my word - as much as it is worth - that what is produced here is my own, unless AI is explicitly mentioned.

Transparency, and being explicit in your assumptions and intentions is something I value highly.

**I use AI for:**

- Quick brainstorming
- Providing a quick backbone of code on which I can build
- Learning how and why code works, under the hood (faster than, but not replacing, looking up documentation)

<!--

List of wants

- [x] testing deployment: rerendering all posts to get thumbnails right
- [x] testing deployment: test to see if i can do dark theme first, and only change about.qmd and _quarto.yml and then push changes - it should work
- [ ] tab with
  - [x] updated CV
  - [x] Some Publications
  - [ ] Dashboard (overview/listing of several?) - at minimum something something developments in danish medicine use or something
 -->
