
May not want to include this until i have some better projects

NB: maybe just copy the concept and use it for publications

# Projects

See my [github profile](https://github.com/schochastics) for a comprehensive list of open source projects.

```{r}
#| label: proj
#| output: asis
tibble::tribble(
    ~what, ~role, ~items,
    "R packages", "Creator and Maintainer", c("edgebundle", "graphlayouts", "levelnet", "netrankr", "netUtils", "networkdata", "PSAWR", "roughnet", "roughsf", "rtoot", "Rtumblr", "signnet", "snahelper", "webbotparseR", "webtrackR"),
    "R packages", "Contributor", c("backbone", "ggraph", "multigraphr", "netropy", "rang", "rgraph6"),
    "Quarto extensions", "Creator and Maintainer",
    c("Academicons (shortcodes)", "Blackboard (revealjs theme)", "sketchy (html theme)", "share buttons (filter)", "nutshell (filter)", "quartocities (website template)", "quartocv (cv templates)"),
    "soccerverse.com (football analytics website)", "Creator and Maintainer",
    c(
        "Manual and automated gathering of football results around the world",
        "Harmonizing data (e.g. club names and managers)",
        "Implementation of ranking algorithms",
        "Predicting of league tables and matchforecasting",
        "Uses R, JavaScript, HTML, and CSS",
        "around 1000 visitors/month"
    )
) |>
    cvproj(what = "what", role = "role", items = "items")

``` 

    - name: Education
      items:
        - text: "Master’s Degree - Medical Market Access"
          inst: "Aalborg University"
          time: "2014 - 2017"
          details: "Health conomics, medical market access, quality improvement, bigger picture thinking"
          #Old text shortened:"Although my Master’s degree focused mainly on Health Economics, I have also gained knowledge
          #of the medical market access process in general, as well as the process of quality improvement.
          #My interest in data and all its aspects began here, with a course in Econometrics using Stata."
        - text: "Bachelor Degree - Medicine With Industrial Specialisation"
          inst: "Aalborg University"
          time: "2011 - 2014"
          details: "A solid foundational understanding of medicine fueling understanding of health data"
          #Old text shortened:Three years studying medicine on par with other students of medicine taught me the foundation
          #for understanding both patient health data and finding connections between several independent
          #signals. This has helped me better understand what goes on behind the scenes of creating health
          #datasets.

-->


tibble::tribble(
    ~what, ~role, ~items,
    "R packages", "Creator and Maintainer", c("edgebundle", "graphlayouts", "levelnet", "netrankr", "netUtils", "networkdata", "PSAWR", "roughnet", "roughsf", "rtoot", "Rtumblr", "signnet", "snahelper", "webbotparseR", "webtrackR"),
    "R packages", "Contributor", c("backbone", "ggraph", "multigraphr", "netropy", "rang", "rgraph6"),
    "Quarto extensions", "Creator and Maintainer",
    c("Academicons (shortcodes)", "Blackboard (revealjs theme)", "sketchy (html theme)", "share buttons (filter)", "nutshell (filter)", "quartocities (website template)", "quartocv (cv templates)"),
    "soccerverse.com (football analytics website)", "Creator and Maintainer",
    c(
        "Manual and automated gathering of football results around the world",
        "Harmonizing data (e.g. club names and managers)",
        "Implementation of ranking algorithms",
        "Predicting of league tables and matchforecasting",
        "Uses R, JavaScript, HTML, and CSS",
        "around 1000 visitors/month"
    )
) |>
    cvproj(what = "what", role = "role", items = "items")
