```{r}
#| label: experience
#| output: asis
tibble::tribble(
    #"Position X", "Where", "When", "Details"    
    ~role, ~institution, ~dates, ~details,
    "Ph.D student", "Aalborg University and Steno Diabetes Center North Denmark", "04/2020 - Present", "My Ph.D. combines systematically reviewing cost-effectiveness analyses of medications for treating Type 2 Diabetes, with testing assumptions in these decision-analytical models against real-world data, further developing my expertise in epidemiological study design. I have taken courses in biostatistics, advanced epidemiology, time to event analysis, and decision-analytical modelling using R.",
    "Data Manager", "Steno Diabetes Center North Denmark", "01/2019 - 03/2020", "In this position I gained expertise in epidemiological study design, data wrangling, analysis, and presentation. In dialogue with medical doctors, we defined the cohorts necessary to answer research questions regarding treatment and outcomes for patients with Diabetes Mellitus or Osteoporosis.",
    "Scientific Assistant", "Danish Center for Healthcare Improvements", "11/2017 - 08/2018", "I finished my first systematic review and investigated methodological challenges regarding cost-analysis of extremely expensive haematological medications.",

) |>
    cvevents(when = "dates", what = "role", where = "institution", descr = "details")
```

```{r}
#| label: education
#| output: asis
    # Education name and dates, education place, education description
    # Journal - year, DOI, publication title and description
tibble::tribble(
    ~what, ~role, ~items,
    whats[1], roles[1], items[1],
    whats[2], roles[2], items[2],
    whats[3], roles[3], items[3],
    whats[4], roles[4], items[4],
    "Master: Medical Market Access","Aalborg University 2014 - 2017" ,"Health conomics, medical market access, quality improvement, big picture and detail-level pragmatic thinking.",
    "Bachelor: Medicine With Industrial Specialisation","Aalborg University 2011 - 2014" ,"A solid foundation in medicine to understand and utilise health data.",
    "PharmacoEconomics Journal - 2023","DOI: 10.1007/s40273-023-01268-5","A Systematic Review of Cost-Effectiveness Studies of Newer Non-Insulin Antidiabetic Drugs: Trends in Decision-Analytical Models for Modelling of Type 2 Diabetes Mellitus - The bulk of my phd was spent with me working on this review.",
    "Current Drug Safety - 2020","DOI:10.2174/1574886315666200819114629","Sodium glucose cotransporter-2 inhibitor treatment and the risk of diabetic ketoacidosis in Denmark: A retrospective cohort study of five years of use. I did all data management and statistics.",
    "Diabetic Medicine - 2020","DOI: 10.1111/dme.14251","Twenty years with diabetes and amputations: a retrospective population-based cohort study. I did the data management and some statistics.",

) |>
    cvproj(what = "what", role = "role", items = "items")
```

<!-- older version:
I am a passionate and inquisitive health data scientist, that loves to combine my expertise in medicine, data analysis, health economics, and systematic reviewing to . I love and excel at uncovering insights from complex datasets, leveraging my deep understanding of medicine and my commitment to translating data into actionable knowledge. My goal is to bridge the gap between data and decision-making in healthcare, delivering clear, impactful results. -->